/*
 * Generated by Bluespec Compiler, version 2017.07.A (build 1da80f1, 2017-07-21)
 * 
 * On Wed Aug 15 16:00:33 BST 2018
 * 
 */

/* Generation options: */
#ifndef __mkFabric_h__
#define __mkFabric_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"
#include "mkSoC_Map.h"


/* Class declaration for the mkFabric module */
class MOD_mkFabric : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_ConfigReg<tUInt8> INST_fabric_cfg_verbosity;
  MOD_Fifo<tUInt8> INST_fabric_v_f_rd_err_user_0;
  MOD_Fifo<tUInt8> INST_fabric_v_f_rd_err_user_1;
  MOD_Fifo<tUInt8> INST_fabric_v_f_rd_err_user_2;
  MOD_Fifo<tUInt8> INST_fabric_v_f_rd_mis_0;
  MOD_Fifo<tUInt8> INST_fabric_v_f_rd_mis_1;
  MOD_Fifo<tUInt8> INST_fabric_v_f_rd_mis_2;
  MOD_Fifo<tUInt8> INST_fabric_v_f_rd_mis_3;
  MOD_Fifo<tUInt8> INST_fabric_v_f_rd_mis_4;
  MOD_Fifo<tUInt8> INST_fabric_v_f_rd_sjs_0;
  MOD_Fifo<tUInt8> INST_fabric_v_f_rd_sjs_1;
  MOD_Fifo<tUInt8> INST_fabric_v_f_rd_sjs_2;
  MOD_Fifo<tUInt8> INST_fabric_v_f_wr_err_user_0;
  MOD_Fifo<tUInt8> INST_fabric_v_f_wr_err_user_1;
  MOD_Fifo<tUInt8> INST_fabric_v_f_wr_err_user_2;
  MOD_Fifo<tUInt8> INST_fabric_v_f_wr_mis_0;
  MOD_Fifo<tUInt8> INST_fabric_v_f_wr_mis_1;
  MOD_Fifo<tUInt8> INST_fabric_v_f_wr_mis_2;
  MOD_Fifo<tUInt8> INST_fabric_v_f_wr_mis_3;
  MOD_Fifo<tUInt8> INST_fabric_v_f_wr_mis_4;
  MOD_Fifo<tUInt8> INST_fabric_v_f_wr_sjs_0;
  MOD_Fifo<tUInt8> INST_fabric_v_f_wr_sjs_1;
  MOD_Fifo<tUInt8> INST_fabric_v_f_wr_sjs_2;
  MOD_Fifo<tUWide> INST_fabric_xactors_from_masters_0_f_rd_addr;
  MOD_Fifo<tUWide> INST_fabric_xactors_from_masters_0_f_rd_data;
  MOD_Fifo<tUWide> INST_fabric_xactors_from_masters_0_f_wr_addr;
  MOD_Fifo<tUWide> INST_fabric_xactors_from_masters_0_f_wr_data;
  MOD_Fifo<tUInt8> INST_fabric_xactors_from_masters_0_f_wr_resp;
  MOD_Fifo<tUWide> INST_fabric_xactors_from_masters_1_f_rd_addr;
  MOD_Fifo<tUWide> INST_fabric_xactors_from_masters_1_f_rd_data;
  MOD_Fifo<tUWide> INST_fabric_xactors_from_masters_1_f_wr_addr;
  MOD_Fifo<tUWide> INST_fabric_xactors_from_masters_1_f_wr_data;
  MOD_Fifo<tUInt8> INST_fabric_xactors_from_masters_1_f_wr_resp;
  MOD_Fifo<tUWide> INST_fabric_xactors_from_masters_2_f_rd_addr;
  MOD_Fifo<tUWide> INST_fabric_xactors_from_masters_2_f_rd_data;
  MOD_Fifo<tUWide> INST_fabric_xactors_from_masters_2_f_wr_addr;
  MOD_Fifo<tUWide> INST_fabric_xactors_from_masters_2_f_wr_data;
  MOD_Fifo<tUInt8> INST_fabric_xactors_from_masters_2_f_wr_resp;
  MOD_Fifo<tUWide> INST_fabric_xactors_to_slaves_0_f_rd_addr;
  MOD_Fifo<tUWide> INST_fabric_xactors_to_slaves_0_f_rd_data;
  MOD_Fifo<tUWide> INST_fabric_xactors_to_slaves_0_f_wr_addr;
  MOD_Fifo<tUWide> INST_fabric_xactors_to_slaves_0_f_wr_data;
  MOD_Fifo<tUInt8> INST_fabric_xactors_to_slaves_0_f_wr_resp;
  MOD_Fifo<tUWide> INST_fabric_xactors_to_slaves_1_f_rd_addr;
  MOD_Fifo<tUWide> INST_fabric_xactors_to_slaves_1_f_rd_data;
  MOD_Fifo<tUWide> INST_fabric_xactors_to_slaves_1_f_wr_addr;
  MOD_Fifo<tUWide> INST_fabric_xactors_to_slaves_1_f_wr_data;
  MOD_Fifo<tUInt8> INST_fabric_xactors_to_slaves_1_f_wr_resp;
  MOD_Fifo<tUWide> INST_fabric_xactors_to_slaves_2_f_rd_addr;
  MOD_Fifo<tUWide> INST_fabric_xactors_to_slaves_2_f_rd_data;
  MOD_Fifo<tUWide> INST_fabric_xactors_to_slaves_2_f_wr_addr;
  MOD_Fifo<tUWide> INST_fabric_xactors_to_slaves_2_f_wr_data;
  MOD_Fifo<tUInt8> INST_fabric_xactors_to_slaves_2_f_wr_resp;
  MOD_Fifo<tUWide> INST_fabric_xactors_to_slaves_3_f_rd_addr;
  MOD_Fifo<tUWide> INST_fabric_xactors_to_slaves_3_f_rd_data;
  MOD_Fifo<tUWide> INST_fabric_xactors_to_slaves_3_f_wr_addr;
  MOD_Fifo<tUWide> INST_fabric_xactors_to_slaves_3_f_wr_data;
  MOD_Fifo<tUInt8> INST_fabric_xactors_to_slaves_3_f_wr_resp;
  MOD_Fifo<tUWide> INST_fabric_xactors_to_slaves_4_f_rd_addr;
  MOD_Fifo<tUWide> INST_fabric_xactors_to_slaves_4_f_rd_data;
  MOD_Fifo<tUWide> INST_fabric_xactors_to_slaves_4_f_wr_addr;
  MOD_Fifo<tUWide> INST_fabric_xactors_to_slaves_4_f_wr_data;
  MOD_Fifo<tUInt8> INST_fabric_xactors_to_slaves_4_f_wr_resp;
  MOD_mkSoC_Map INST_soc_map;
 
 /* Constructor */
 public:
  MOD_mkFabric(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
  tUInt8 PORT_v_from_masters_0_awready;
  tUInt8 PORT_v_from_masters_0_wready;
  tUInt8 PORT_v_from_masters_0_bvalid;
  tUInt8 PORT_v_from_masters_0_bresp;
  tUInt8 PORT_v_from_masters_0_buser;
  tUInt8 PORT_v_from_masters_0_arready;
  tUInt8 PORT_v_from_masters_0_rvalid;
  tUInt8 PORT_v_from_masters_0_rresp;
  tUInt64 PORT_v_from_masters_0_rdata;
  tUInt8 PORT_v_from_masters_0_ruser;
  tUInt8 PORT_v_from_masters_1_awready;
  tUInt8 PORT_v_from_masters_1_wready;
  tUInt8 PORT_v_from_masters_1_bvalid;
  tUInt8 PORT_v_from_masters_1_bresp;
  tUInt8 PORT_v_from_masters_1_buser;
  tUInt8 PORT_v_from_masters_1_arready;
  tUInt8 PORT_v_from_masters_1_rvalid;
  tUInt8 PORT_v_from_masters_1_rresp;
  tUInt64 PORT_v_from_masters_1_rdata;
  tUInt8 PORT_v_from_masters_1_ruser;
  tUInt8 PORT_v_from_masters_2_awready;
  tUInt8 PORT_v_from_masters_2_wready;
  tUInt8 PORT_v_from_masters_2_bvalid;
  tUInt8 PORT_v_from_masters_2_bresp;
  tUInt8 PORT_v_from_masters_2_buser;
  tUInt8 PORT_v_from_masters_2_arready;
  tUInt8 PORT_v_from_masters_2_rvalid;
  tUInt8 PORT_v_from_masters_2_rresp;
  tUInt64 PORT_v_from_masters_2_rdata;
  tUInt8 PORT_v_from_masters_2_ruser;
  tUInt8 PORT_v_to_slaves_0_awvalid;
  tUInt64 PORT_v_to_slaves_0_awaddr;
  tUInt8 PORT_v_to_slaves_0_awprot;
  tUInt8 PORT_v_to_slaves_0_awuser;
  tUInt8 PORT_v_to_slaves_0_wvalid;
  tUInt64 PORT_v_to_slaves_0_wdata;
  tUInt8 PORT_v_to_slaves_0_wstrb;
  tUInt8 PORT_v_to_slaves_0_bready;
  tUInt8 PORT_v_to_slaves_0_arvalid;
  tUInt64 PORT_v_to_slaves_0_araddr;
  tUInt8 PORT_v_to_slaves_0_arprot;
  tUInt8 PORT_v_to_slaves_0_aruser;
  tUInt8 PORT_v_to_slaves_0_rready;
  tUInt8 PORT_v_to_slaves_1_awvalid;
  tUInt64 PORT_v_to_slaves_1_awaddr;
  tUInt8 PORT_v_to_slaves_1_awprot;
  tUInt8 PORT_v_to_slaves_1_awuser;
  tUInt8 PORT_v_to_slaves_1_wvalid;
  tUInt64 PORT_v_to_slaves_1_wdata;
  tUInt8 PORT_v_to_slaves_1_wstrb;
  tUInt8 PORT_v_to_slaves_1_bready;
  tUInt8 PORT_v_to_slaves_1_arvalid;
  tUInt64 PORT_v_to_slaves_1_araddr;
  tUInt8 PORT_v_to_slaves_1_arprot;
  tUInt8 PORT_v_to_slaves_1_aruser;
  tUInt8 PORT_v_to_slaves_1_rready;
  tUInt8 PORT_v_to_slaves_2_awvalid;
  tUInt64 PORT_v_to_slaves_2_awaddr;
  tUInt8 PORT_v_to_slaves_2_awprot;
  tUInt8 PORT_v_to_slaves_2_awuser;
  tUInt8 PORT_v_to_slaves_2_wvalid;
  tUInt64 PORT_v_to_slaves_2_wdata;
  tUInt8 PORT_v_to_slaves_2_wstrb;
  tUInt8 PORT_v_to_slaves_2_bready;
  tUInt8 PORT_v_to_slaves_2_arvalid;
  tUInt64 PORT_v_to_slaves_2_araddr;
  tUInt8 PORT_v_to_slaves_2_arprot;
  tUInt8 PORT_v_to_slaves_2_aruser;
  tUInt8 PORT_v_to_slaves_2_rready;
  tUInt8 PORT_v_to_slaves_3_awvalid;
  tUInt64 PORT_v_to_slaves_3_awaddr;
  tUInt8 PORT_v_to_slaves_3_awprot;
  tUInt8 PORT_v_to_slaves_3_awuser;
  tUInt8 PORT_v_to_slaves_3_wvalid;
  tUInt64 PORT_v_to_slaves_3_wdata;
  tUInt8 PORT_v_to_slaves_3_wstrb;
  tUInt8 PORT_v_to_slaves_3_bready;
  tUInt8 PORT_v_to_slaves_3_arvalid;
  tUInt64 PORT_v_to_slaves_3_araddr;
  tUInt8 PORT_v_to_slaves_3_arprot;
  tUInt8 PORT_v_to_slaves_3_aruser;
  tUInt8 PORT_v_to_slaves_3_rready;
  tUInt8 PORT_v_to_slaves_4_awvalid;
  tUInt64 PORT_v_to_slaves_4_awaddr;
  tUInt8 PORT_v_to_slaves_4_awprot;
  tUInt8 PORT_v_to_slaves_4_awuser;
  tUInt8 PORT_v_to_slaves_4_wvalid;
  tUInt64 PORT_v_to_slaves_4_wdata;
  tUInt8 PORT_v_to_slaves_4_wstrb;
  tUInt8 PORT_v_to_slaves_4_bready;
  tUInt8 PORT_v_to_slaves_4_arvalid;
  tUInt64 PORT_v_to_slaves_4_araddr;
  tUInt8 PORT_v_to_slaves_4_arprot;
  tUInt8 PORT_v_to_slaves_4_aruser;
  tUInt8 PORT_v_to_slaves_4_rready;
  tUInt8 PORT_RDY_v_from_masters_0_m_awvalid;
  tUInt8 PORT_RDY_v_from_masters_0_m_wvalid;
  tUInt8 PORT_RDY_v_from_masters_0_m_bready;
  tUInt8 PORT_RDY_v_from_masters_0_m_arvalid;
  tUInt8 PORT_RDY_v_from_masters_0_m_rready;
  tUInt8 PORT_RDY_v_from_masters_1_m_awvalid;
  tUInt8 PORT_RDY_v_from_masters_1_m_wvalid;
  tUInt8 PORT_RDY_v_from_masters_1_m_bready;
  tUInt8 PORT_RDY_v_from_masters_1_m_arvalid;
  tUInt8 PORT_RDY_v_from_masters_1_m_rready;
  tUInt8 PORT_RDY_v_from_masters_2_m_awvalid;
  tUInt8 PORT_RDY_v_from_masters_2_m_wvalid;
  tUInt8 PORT_RDY_v_from_masters_2_m_bready;
  tUInt8 PORT_RDY_v_from_masters_2_m_arvalid;
  tUInt8 PORT_RDY_v_from_masters_2_m_rready;
  tUInt8 PORT_RDY_v_to_slaves_0_m_awready;
  tUInt8 PORT_RDY_v_to_slaves_0_m_wready;
  tUInt8 PORT_RDY_v_to_slaves_0_m_bvalid;
  tUInt8 PORT_RDY_v_to_slaves_0_m_arready;
  tUInt8 PORT_RDY_v_to_slaves_0_m_rvalid;
  tUInt8 PORT_RDY_v_to_slaves_1_m_awready;
  tUInt8 PORT_RDY_v_to_slaves_1_m_wready;
  tUInt8 PORT_RDY_v_to_slaves_1_m_bvalid;
  tUInt8 PORT_RDY_v_to_slaves_1_m_arready;
  tUInt8 PORT_RDY_v_to_slaves_1_m_rvalid;
  tUInt8 PORT_RDY_v_to_slaves_2_m_awready;
  tUInt8 PORT_RDY_v_to_slaves_2_m_wready;
  tUInt8 PORT_RDY_v_to_slaves_2_m_bvalid;
  tUInt8 PORT_RDY_v_to_slaves_2_m_arready;
  tUInt8 PORT_RDY_v_to_slaves_2_m_rvalid;
  tUInt8 PORT_RDY_v_to_slaves_3_m_awready;
  tUInt8 PORT_RDY_v_to_slaves_3_m_wready;
  tUInt8 PORT_RDY_v_to_slaves_3_m_bvalid;
  tUInt8 PORT_RDY_v_to_slaves_3_m_arready;
  tUInt8 PORT_RDY_v_to_slaves_3_m_rvalid;
  tUInt8 PORT_RDY_v_to_slaves_4_m_awready;
  tUInt8 PORT_RDY_v_to_slaves_4_m_wready;
  tUInt8 PORT_RDY_v_to_slaves_4_m_bvalid;
  tUInt8 PORT_RDY_v_to_slaves_4_m_arready;
  tUInt8 PORT_RDY_v_to_slaves_4_m_rvalid;
 
 /* Publicly accessible definitions */
 public:
  tUWide DEF_fabric_xactors_from_masters_2_f_rd_addr_first____d455;
  tUWide DEF_fabric_xactors_from_masters_2_f_wr_addr_first____d188;
  tUWide DEF_fabric_xactors_from_masters_1_f_rd_addr_first____d395;
  tUWide DEF_fabric_xactors_from_masters_1_f_wr_addr_first____d118;
  tUWide DEF_fabric_xactors_from_masters_0_f_rd_addr_first____d323;
  tUWide DEF_fabric_xactors_from_masters_0_f_wr_addr_first____d13;
  tUInt64 DEF_fabric_xactors_from_masters_2_f_rd_addr_first__ETC___d456;
  tUInt64 DEF_fabric_xactors_from_masters_1_f_rd_addr_first__ETC___d396;
  tUInt64 DEF_fabric_xactors_from_masters_0_f_rd_addr_first__ETC___d324;
  tUInt64 DEF_fabric_xactors_from_masters_2_f_wr_addr_first__ETC___d189;
  tUInt64 DEF_fabric_xactors_from_masters_1_f_wr_addr_first__ETC___d119;
  tUInt64 DEF_fabric_xactors_from_masters_0_f_wr_addr_first__ETC___d14;
 
 /* Local definitions */
 private:
  tUInt32 DEF_v__h32341;
  tUInt32 DEF_v__h32115;
  tUInt32 DEF_v__h31889;
  tUInt32 DEF_v__h31608;
  tUInt32 DEF_v__h31324;
  tUInt32 DEF_v__h31040;
  tUInt32 DEF_v__h30756;
  tUInt32 DEF_v__h30472;
  tUInt32 DEF_v__h30149;
  tUInt32 DEF_v__h29865;
  tUInt32 DEF_v__h29581;
  tUInt32 DEF_v__h29297;
  tUInt32 DEF_v__h29013;
  tUInt32 DEF_v__h28690;
  tUInt32 DEF_v__h28379;
  tUInt32 DEF_v__h28068;
  tUInt32 DEF_v__h27757;
  tUInt32 DEF_v__h27446;
  tUInt32 DEF_v__h27115;
  tUInt32 DEF_v__h26892;
  tUInt32 DEF_v__h26669;
  tUInt32 DEF_v__h26392;
  tUInt32 DEF_v__h26112;
  tUInt32 DEF_v__h25832;
  tUInt32 DEF_v__h25552;
  tUInt32 DEF_v__h25272;
  tUInt32 DEF_v__h24954;
  tUInt32 DEF_v__h24674;
  tUInt32 DEF_v__h24394;
  tUInt32 DEF_v__h24114;
  tUInt32 DEF_v__h23834;
  tUInt32 DEF_v__h23516;
  tUInt32 DEF_v__h23214;
  tUInt32 DEF_v__h22912;
  tUInt32 DEF_v__h22610;
  tUInt32 DEF_v__h22308;
  tUInt32 DEF_v__h21984;
  tUInt32 DEF_v__h21696;
  tUInt32 DEF_v__h21408;
  tUInt32 DEF_v__h20987;
  tUInt32 DEF_v__h20655;
  tUInt32 DEF_v__h20323;
  tUInt32 DEF_v__h19991;
  tUInt32 DEF_v__h19659;
  tUInt32 DEF_v__h19278;
  tUInt32 DEF_v__h18946;
  tUInt32 DEF_v__h18614;
  tUInt32 DEF_v__h18282;
  tUInt32 DEF_v__h17950;
  tUInt32 DEF_v__h17569;
  tUInt32 DEF_v__h17225;
  tUInt32 DEF_v__h16881;
  tUInt32 DEF_v__h16537;
  tUInt32 DEF_v__h16193;
  tUInt32 DEF_v__h15551;
  tUInt32 DEF_v__h15217;
  tUInt32 DEF_v__h14883;
  tUInt32 DEF_v__h14387;
  tUInt32 DEF_v__h13944;
  tUInt32 DEF_v__h13501;
  tUInt32 DEF_v__h13058;
  tUInt32 DEF_v__h12615;
  tUInt32 DEF_v__h12107;
  tUInt32 DEF_v__h11664;
  tUInt32 DEF_v__h11221;
  tUInt32 DEF_v__h10778;
  tUInt32 DEF_v__h10335;
  tUInt32 DEF_v__h9827;
  tUInt32 DEF_v__h9367;
  tUInt32 DEF_v__h8907;
  tUInt32 DEF_v__h8447;
  tUInt32 DEF_v__h7987;
  tUInt32 DEF_signed_4___d109;
  tUInt32 DEF_signed_3___d95;
  tUInt32 DEF_signed_2___d81;
  tUInt32 DEF_signed_1___d67;
  tUInt32 DEF_signed_0___d50;
  tUWide DEF_fabric_xactors_to_slaves_4_f_wr_data_first____d1159;
  tUWide DEF_fabric_xactors_to_slaves_3_f_wr_data_first____d1145;
  tUWide DEF_fabric_xactors_to_slaves_2_f_wr_data_first____d1131;
  tUWide DEF_fabric_xactors_to_slaves_1_f_wr_data_first____d1117;
  tUWide DEF_fabric_xactors_to_slaves_0_f_wr_data_first____d1103;
  tUWide DEF_fabric_xactors_from_masters_2_f_wr_data_first____d212;
  tUWide DEF_fabric_xactors_from_masters_1_f_wr_data_first____d142;
  tUWide DEF_fabric_xactors_from_masters_0_f_wr_data_first____d44;
  tUWide DEF_fabric_xactors_to_slaves_4_f_rd_addr_first____d1164;
  tUWide DEF_fabric_xactors_to_slaves_4_f_wr_addr_first____d1156;
  tUWide DEF_fabric_xactors_to_slaves_3_f_rd_addr_first____d1150;
  tUWide DEF_fabric_xactors_to_slaves_3_f_wr_addr_first____d1142;
  tUWide DEF_fabric_xactors_to_slaves_2_f_rd_addr_first____d1136;
  tUWide DEF_fabric_xactors_to_slaves_2_f_wr_addr_first____d1128;
  tUWide DEF_fabric_xactors_to_slaves_1_f_rd_addr_first____d1122;
  tUWide DEF_fabric_xactors_to_slaves_1_f_wr_addr_first____d1114;
  tUWide DEF_fabric_xactors_to_slaves_0_f_rd_addr_first____d1108;
  tUWide DEF_fabric_xactors_to_slaves_0_f_wr_addr_first____d1100;
  tUWide DEF_fabric_xactors_to_slaves_4_f_rd_data_first____d931;
  tUWide DEF_fabric_xactors_to_slaves_3_f_rd_data_first____d904;
  tUWide DEF_fabric_xactors_to_slaves_2_f_rd_data_first____d877;
  tUWide DEF_fabric_xactors_to_slaves_1_f_rd_data_first____d850;
  tUWide DEF_fabric_xactors_to_slaves_0_f_rd_data_first____d823;
  tUWide DEF_fabric_xactors_from_masters_2_f_rd_data_first____d1097;
  tUWide DEF_fabric_xactors_from_masters_1_f_rd_data_first____d1083;
  tUWide DEF_fabric_xactors_from_masters_0_f_rd_data_first____d1069;
  tUInt8 DEF__read__h230;
  tUInt8 DEF_fabric_xactors_to_slaves_4_f_wr_resp_first____d686;
  tUInt8 DEF_fabric_xactors_to_slaves_3_f_wr_resp_first____d661;
  tUInt8 DEF_fabric_xactors_to_slaves_2_f_wr_resp_first____d636;
  tUInt8 DEF_fabric_xactors_to_slaves_1_f_wr_resp_first____d611;
  tUInt8 DEF_fabric_xactors_to_slaves_0_f_wr_resp_first____d586;
  tUInt8 DEF_fabric_xactors_to_slaves_4_f_rd_data_i_notFull____d1166;
  tUInt8 DEF_fabric_xactors_to_slaves_4_f_rd_addr_i_notEmpty____d1163;
  tUInt8 DEF_fabric_xactors_to_slaves_4_f_wr_resp_i_notFull____d1161;
  tUInt8 DEF_fabric_xactors_to_slaves_4_f_wr_data_i_notEmpty____d1158;
  tUInt8 DEF_fabric_xactors_to_slaves_4_f_wr_addr_i_notEmpty____d1155;
  tUInt8 DEF_fabric_xactors_to_slaves_3_f_rd_data_i_notFull____d1152;
  tUInt8 DEF_fabric_xactors_to_slaves_3_f_rd_addr_i_notEmpty____d1149;
  tUInt8 DEF_fabric_xactors_to_slaves_3_f_wr_resp_i_notFull____d1147;
  tUInt8 DEF_fabric_xactors_to_slaves_3_f_wr_data_i_notEmpty____d1144;
  tUInt8 DEF_fabric_xactors_to_slaves_3_f_wr_addr_i_notEmpty____d1141;
  tUInt8 DEF_fabric_xactors_to_slaves_2_f_rd_data_i_notFull____d1138;
  tUInt8 DEF_fabric_xactors_to_slaves_2_f_rd_addr_i_notEmpty____d1135;
  tUInt8 DEF_fabric_xactors_to_slaves_2_f_wr_resp_i_notFull____d1133;
  tUInt8 DEF_fabric_xactors_to_slaves_2_f_wr_data_i_notEmpty____d1130;
  tUInt8 DEF_fabric_xactors_to_slaves_2_f_wr_addr_i_notEmpty____d1127;
  tUInt8 DEF_fabric_xactors_to_slaves_1_f_rd_data_i_notFull____d1124;
  tUInt8 DEF_fabric_xactors_to_slaves_1_f_rd_addr_i_notEmpty____d1121;
  tUInt8 DEF_fabric_xactors_to_slaves_1_f_wr_resp_i_notFull____d1119;
  tUInt8 DEF_fabric_xactors_to_slaves_1_f_wr_data_i_notEmpty____d1116;
  tUInt8 DEF_fabric_xactors_to_slaves_1_f_wr_addr_i_notEmpty____d1113;
  tUInt8 DEF_fabric_xactors_to_slaves_0_f_rd_data_i_notFull____d1110;
  tUInt8 DEF_fabric_xactors_to_slaves_0_f_rd_addr_i_notEmpty____d1107;
  tUInt8 DEF_fabric_xactors_to_slaves_0_f_wr_resp_i_notFull____d1105;
  tUInt8 DEF_fabric_xactors_to_slaves_0_f_wr_data_i_notEmpty____d1102;
  tUInt8 DEF_fabric_xactors_to_slaves_0_f_wr_addr_i_notEmpty____d1099;
  tUInt8 DEF_fabric_xactors_from_masters_2_f_rd_data_i_notE_ETC___d1096;
  tUInt8 DEF_fabric_xactors_from_masters_2_f_rd_addr_i_notF_ETC___d1093;
  tUInt8 DEF_fabric_xactors_from_masters_2_f_wr_resp_i_notE_ETC___d1091;
  tUInt8 DEF_fabric_xactors_from_masters_2_f_wr_data_i_notF_ETC___d1088;
  tUInt8 DEF_fabric_xactors_from_masters_2_f_wr_addr_i_notF_ETC___d1085;
  tUInt8 DEF_fabric_xactors_from_masters_1_f_rd_data_i_notE_ETC___d1082;
  tUInt8 DEF_fabric_xactors_from_masters_1_f_rd_addr_i_notF_ETC___d1079;
  tUInt8 DEF_fabric_xactors_from_masters_1_f_wr_resp_i_notE_ETC___d1077;
  tUInt8 DEF_fabric_xactors_from_masters_1_f_wr_data_i_notF_ETC___d1074;
  tUInt8 DEF_fabric_xactors_from_masters_1_f_wr_addr_i_notF_ETC___d1071;
  tUInt8 DEF_fabric_xactors_from_masters_0_f_rd_data_i_notE_ETC___d1068;
  tUInt8 DEF_fabric_xactors_from_masters_0_f_rd_addr_i_notF_ETC___d1065;
  tUInt8 DEF_fabric_xactors_from_masters_0_f_wr_resp_i_notE_ETC___d1063;
  tUInt8 DEF_fabric_xactors_from_masters_0_f_wr_data_i_notF_ETC___d1060;
  tUInt8 DEF_fabric_xactors_from_masters_0_f_wr_addr_i_notF_ETC___d1057;
  tUInt64 DEF_fabric_xactors_from_masters_2_f_wr_data_first__ETC___d216;
  tUInt64 DEF_fabric_xactors_from_masters_0_f_wr_data_first__ETC___d52;
  tUInt64 DEF_fabric_xactors_from_masters_1_f_wr_data_first__ETC___d146;
  tUInt64 DEF_fabric_xactors_to_slaves_4_f_rd_data_first__31_ETC___d947;
  tUInt64 DEF_fabric_xactors_to_slaves_3_f_rd_data_first__04_ETC___d920;
  tUInt64 DEF_fabric_xactors_to_slaves_2_f_rd_data_first__77_ETC___d893;
  tUInt64 DEF_fabric_xactors_to_slaves_1_f_rd_data_first__50_ETC___d866;
  tUInt64 DEF_fabric_xactors_to_slaves_0_f_rd_data_first__23_ETC___d839;
  tUInt8 DEF_fabric_xactors_from_masters_2_f_wr_data_first__ETC___d217;
  tUInt8 DEF_fabric_xactors_from_masters_0_f_wr_data_first__ETC___d53;
  tUInt8 DEF_fabric_xactors_from_masters_1_f_wr_data_first__ETC___d147;
  tUInt8 DEF_fabric_xactors_from_masters_2_f_rd_addr_first__ETC___d481;
  tUInt8 DEF_fabric_xactors_from_masters_1_f_rd_addr_first__ETC___d421;
  tUInt8 DEF_fabric_xactors_from_masters_0_f_rd_addr_first__ETC___d349;
  tUInt8 DEF_fabric_xactors_from_masters_2_f_wr_addr_first__ETC___d215;
  tUInt8 DEF_fabric_xactors_from_masters_1_f_wr_addr_first__ETC___d145;
  tUInt8 DEF_fabric_xactors_from_masters_0_f_wr_addr_first__ETC___d51;
  tUInt8 DEF_fabric_xactors_to_slaves_4_f_rd_data_first__31_ETC___d934;
  tUInt8 DEF_fabric_xactors_to_slaves_3_f_rd_data_first__04_ETC___d907;
  tUInt8 DEF_fabric_xactors_to_slaves_2_f_rd_data_first__77_ETC___d880;
  tUInt8 DEF_fabric_xactors_to_slaves_1_f_rd_data_first__50_ETC___d853;
  tUInt8 DEF_fabric_xactors_to_slaves_0_f_rd_data_first__23_ETC___d826;
  tUInt8 DEF_fabric_xactors_to_slaves_4_f_rd_data_first__31_ETC___d939;
  tUInt8 DEF_fabric_xactors_to_slaves_4_f_rd_data_first__31_ETC___d937;
  tUInt8 DEF_fabric_xactors_to_slaves_4_f_rd_data_first__31_ETC___d935;
  tUInt8 DEF_fabric_xactors_to_slaves_3_f_rd_data_first__04_ETC___d912;
  tUInt8 DEF_fabric_xactors_to_slaves_3_f_rd_data_first__04_ETC___d910;
  tUInt8 DEF_fabric_xactors_to_slaves_3_f_rd_data_first__04_ETC___d908;
  tUInt8 DEF_fabric_xactors_to_slaves_2_f_rd_data_first__77_ETC___d885;
  tUInt8 DEF_fabric_xactors_to_slaves_2_f_rd_data_first__77_ETC___d883;
  tUInt8 DEF_fabric_xactors_to_slaves_2_f_rd_data_first__77_ETC___d881;
  tUInt8 DEF_fabric_xactors_to_slaves_1_f_rd_data_first__50_ETC___d858;
  tUInt8 DEF_fabric_xactors_to_slaves_1_f_rd_data_first__50_ETC___d856;
  tUInt8 DEF_fabric_xactors_to_slaves_1_f_rd_data_first__50_ETC___d854;
  tUInt8 DEF_fabric_xactors_to_slaves_0_f_rd_data_first__23_ETC___d831;
  tUInt8 DEF_fabric_xactors_to_slaves_0_f_rd_data_first__23_ETC___d829;
  tUInt8 DEF_fabric_xactors_to_slaves_0_f_rd_data_first__23_ETC___d827;
  tUInt8 DEF_fabric_xactors_to_slaves_4_f_wr_resp_first__86_ETC___d693;
  tUInt8 DEF_fabric_xactors_to_slaves_4_f_wr_resp_first__86_ETC___d691;
  tUInt8 DEF_fabric_xactors_to_slaves_4_f_wr_resp_first__86_ETC___d689;
  tUInt8 DEF_fabric_xactors_to_slaves_3_f_wr_resp_first__61_ETC___d668;
  tUInt8 DEF_fabric_xactors_to_slaves_3_f_wr_resp_first__61_ETC___d666;
  tUInt8 DEF_fabric_xactors_to_slaves_3_f_wr_resp_first__61_ETC___d664;
  tUInt8 DEF_fabric_xactors_to_slaves_2_f_wr_resp_first__36_ETC___d643;
  tUInt8 DEF_fabric_xactors_to_slaves_2_f_wr_resp_first__36_ETC___d641;
  tUInt8 DEF_fabric_xactors_to_slaves_2_f_wr_resp_first__36_ETC___d639;
  tUInt8 DEF_fabric_xactors_to_slaves_1_f_wr_resp_first__11_ETC___d618;
  tUInt8 DEF_fabric_xactors_to_slaves_1_f_wr_resp_first__11_ETC___d616;
  tUInt8 DEF_fabric_xactors_to_slaves_1_f_wr_resp_first__11_ETC___d614;
  tUInt8 DEF_fabric_xactors_to_slaves_0_f_wr_resp_first__86_ETC___d593;
  tUInt8 DEF_fabric_xactors_to_slaves_0_f_wr_resp_first__86_ETC___d591;
  tUInt8 DEF_fabric_xactors_to_slaves_0_f_wr_resp_first__86_ETC___d589;
  tUInt8 DEF_NOT_fabric_cfg_verbosity_read__5_ULE_1_6_7_AND_ETC___d946;
  tUInt8 DEF_NOT_fabric_cfg_verbosity_read__5_ULE_1_6___d47;
  tUInt8 DEF_NOT_fabric_cfg_verbosity_read__5_ULE_1_6_7_AND_ETC___d940;
  tUInt8 DEF_NOT_fabric_cfg_verbosity_read__5_ULE_1_6_7_AND_ETC___d938;
  tUInt8 DEF_NOT_fabric_cfg_verbosity_read__5_ULE_1_6_7_AND_ETC___d936;
  tUInt8 DEF_NOT_fabric_cfg_verbosity_read__5_ULE_1_6_7_AND_ETC___d919;
  tUInt8 DEF_NOT_fabric_cfg_verbosity_read__5_ULE_1_6_7_AND_ETC___d913;
  tUInt8 DEF_NOT_fabric_cfg_verbosity_read__5_ULE_1_6_7_AND_ETC___d911;
  tUInt8 DEF_NOT_fabric_cfg_verbosity_read__5_ULE_1_6_7_AND_ETC___d909;
  tUInt8 DEF_NOT_fabric_cfg_verbosity_read__5_ULE_1_6_7_AND_ETC___d892;
  tUInt8 DEF_NOT_fabric_cfg_verbosity_read__5_ULE_1_6_7_AND_ETC___d886;
  tUInt8 DEF_NOT_fabric_cfg_verbosity_read__5_ULE_1_6_7_AND_ETC___d884;
  tUInt8 DEF_NOT_fabric_cfg_verbosity_read__5_ULE_1_6_7_AND_ETC___d882;
  tUInt8 DEF_NOT_fabric_cfg_verbosity_read__5_ULE_1_6_7_AND_ETC___d865;
  tUInt8 DEF_NOT_fabric_cfg_verbosity_read__5_ULE_1_6_7_AND_ETC___d859;
  tUInt8 DEF_NOT_fabric_cfg_verbosity_read__5_ULE_1_6_7_AND_ETC___d857;
  tUInt8 DEF_NOT_fabric_cfg_verbosity_read__5_ULE_1_6_7_AND_ETC___d855;
  tUInt8 DEF_NOT_fabric_cfg_verbosity_read__5_ULE_1_6_7_AND_ETC___d838;
  tUInt8 DEF_NOT_fabric_cfg_verbosity_read__5_ULE_1_6_7_AND_ETC___d832;
  tUInt8 DEF_NOT_fabric_cfg_verbosity_read__5_ULE_1_6_7_AND_ETC___d830;
  tUInt8 DEF_NOT_fabric_cfg_verbosity_read__5_ULE_1_6_7_AND_ETC___d828;
  tUInt8 DEF_NOT_fabric_cfg_verbosity_read__5_ULE_1_6_7_AND_ETC___d700;
  tUInt8 DEF_NOT_fabric_cfg_verbosity_read__5_ULE_1_6_7_AND_ETC___d694;
  tUInt8 DEF_NOT_fabric_cfg_verbosity_read__5_ULE_1_6_7_AND_ETC___d692;
  tUInt8 DEF_NOT_fabric_cfg_verbosity_read__5_ULE_1_6_7_AND_ETC___d690;
  tUInt8 DEF_NOT_fabric_cfg_verbosity_read__5_ULE_1_6_7_AND_ETC___d675;
  tUInt8 DEF_NOT_fabric_cfg_verbosity_read__5_ULE_1_6_7_AND_ETC___d669;
  tUInt8 DEF_NOT_fabric_cfg_verbosity_read__5_ULE_1_6_7_AND_ETC___d667;
  tUInt8 DEF_NOT_fabric_cfg_verbosity_read__5_ULE_1_6_7_AND_ETC___d665;
  tUInt8 DEF_NOT_fabric_cfg_verbosity_read__5_ULE_1_6_7_AND_ETC___d650;
  tUInt8 DEF_NOT_fabric_cfg_verbosity_read__5_ULE_1_6_7_AND_ETC___d644;
  tUInt8 DEF_NOT_fabric_cfg_verbosity_read__5_ULE_1_6_7_AND_ETC___d642;
  tUInt8 DEF_NOT_fabric_cfg_verbosity_read__5_ULE_1_6_7_AND_ETC___d640;
  tUInt8 DEF_NOT_fabric_cfg_verbosity_read__5_ULE_1_6_7_AND_ETC___d625;
  tUInt8 DEF_NOT_fabric_cfg_verbosity_read__5_ULE_1_6_7_AND_ETC___d619;
  tUInt8 DEF_NOT_fabric_cfg_verbosity_read__5_ULE_1_6_7_AND_ETC___d617;
  tUInt8 DEF_NOT_fabric_cfg_verbosity_read__5_ULE_1_6_7_AND_ETC___d615;
  tUInt8 DEF_NOT_fabric_cfg_verbosity_read__5_ULE_1_6_7_AND_ETC___d600;
  tUInt8 DEF_NOT_fabric_cfg_verbosity_read__5_ULE_1_6_7_AND_ETC___d594;
  tUInt8 DEF_NOT_fabric_cfg_verbosity_read__5_ULE_1_6_7_AND_ETC___d590;
  tUInt8 DEF_NOT_fabric_cfg_verbosity_read__5_ULE_1_6_7_AND_ETC___d592;
  tUWide DEF_v_from_masters_2_wdata_CONCAT_v_from_masters_2_ETC___d1090;
  tUWide DEF_v_from_masters_1_wdata_CONCAT_v_from_masters_1_ETC___d1076;
  tUWide DEF_v_from_masters_0_wdata_CONCAT_v_from_masters_0_ETC___d1062;
  tUWide DEF_v_from_masters_2_araddr_CONCAT_v_from_masters__ETC___d1095;
  tUWide DEF_v_from_masters_2_awaddr_CONCAT_v_from_masters__ETC___d1087;
  tUWide DEF_v_from_masters_1_araddr_CONCAT_v_from_masters__ETC___d1081;
  tUWide DEF_v_from_masters_1_awaddr_CONCAT_v_from_masters__ETC___d1073;
  tUWide DEF_v_from_masters_0_araddr_CONCAT_v_from_masters__ETC___d1067;
  tUWide DEF_v_from_masters_0_awaddr_CONCAT_v_from_masters__ETC___d1059;
  tUWide DEF_v_to_slaves_4_rresp_CONCAT_v_to_slaves_4_rdata___d1168;
  tUWide DEF_v_to_slaves_3_rresp_CONCAT_v_to_slaves_3_rdata___d1154;
  tUWide DEF_v_to_slaves_2_rresp_CONCAT_v_to_slaves_2_rdata___d1140;
  tUWide DEF_v_to_slaves_1_rresp_CONCAT_v_to_slaves_1_rdata___d1126;
  tUWide DEF_v_to_slaves_0_rresp_CONCAT_v_to_slaves_0_rdata___d1112;
 
 /* Rules */
 public:
  void RL_fabric_rl_wr_xaction_master_to_slave();
  void RL_fabric_rl_wr_xaction_master_to_slave_1();
  void RL_fabric_rl_wr_xaction_master_to_slave_2();
  void RL_fabric_rl_wr_xaction_master_to_slave_3();
  void RL_fabric_rl_wr_xaction_master_to_slave_4();
  void RL_fabric_rl_wr_xaction_master_to_slave_5();
  void RL_fabric_rl_wr_xaction_master_to_slave_6();
  void RL_fabric_rl_wr_xaction_master_to_slave_7();
  void RL_fabric_rl_wr_xaction_master_to_slave_8();
  void RL_fabric_rl_wr_xaction_master_to_slave_9();
  void RL_fabric_rl_wr_xaction_master_to_slave_10();
  void RL_fabric_rl_wr_xaction_master_to_slave_11();
  void RL_fabric_rl_wr_xaction_master_to_slave_12();
  void RL_fabric_rl_wr_xaction_master_to_slave_13();
  void RL_fabric_rl_wr_xaction_master_to_slave_14();
  void RL_fabric_rl_wr_xaction_no_such_slave();
  void RL_fabric_rl_wr_xaction_no_such_slave_1();
  void RL_fabric_rl_wr_xaction_no_such_slave_2();
  void RL_fabric_rl_rd_xaction_master_to_slave();
  void RL_fabric_rl_rd_xaction_master_to_slave_1();
  void RL_fabric_rl_rd_xaction_master_to_slave_2();
  void RL_fabric_rl_rd_xaction_master_to_slave_3();
  void RL_fabric_rl_rd_xaction_master_to_slave_4();
  void RL_fabric_rl_rd_xaction_master_to_slave_5();
  void RL_fabric_rl_rd_xaction_master_to_slave_6();
  void RL_fabric_rl_rd_xaction_master_to_slave_7();
  void RL_fabric_rl_rd_xaction_master_to_slave_8();
  void RL_fabric_rl_rd_xaction_master_to_slave_9();
  void RL_fabric_rl_rd_xaction_master_to_slave_10();
  void RL_fabric_rl_rd_xaction_master_to_slave_11();
  void RL_fabric_rl_rd_xaction_master_to_slave_12();
  void RL_fabric_rl_rd_xaction_master_to_slave_13();
  void RL_fabric_rl_rd_xaction_master_to_slave_14();
  void RL_fabric_rl_rd_xaction_no_such_slave();
  void RL_fabric_rl_rd_xaction_no_such_slave_1();
  void RL_fabric_rl_rd_xaction_no_such_slave_2();
  void RL_fabric_rl_wr_resp_slave_to_master();
  void RL_fabric_rl_wr_resp_slave_to_master_1();
  void RL_fabric_rl_wr_resp_slave_to_master_2();
  void RL_fabric_rl_wr_resp_slave_to_master_3();
  void RL_fabric_rl_wr_resp_slave_to_master_4();
  void RL_fabric_rl_wr_resp_slave_to_master_5();
  void RL_fabric_rl_wr_resp_slave_to_master_6();
  void RL_fabric_rl_wr_resp_slave_to_master_7();
  void RL_fabric_rl_wr_resp_slave_to_master_8();
  void RL_fabric_rl_wr_resp_slave_to_master_9();
  void RL_fabric_rl_wr_resp_slave_to_master_10();
  void RL_fabric_rl_wr_resp_slave_to_master_11();
  void RL_fabric_rl_wr_resp_slave_to_master_12();
  void RL_fabric_rl_wr_resp_slave_to_master_13();
  void RL_fabric_rl_wr_resp_slave_to_master_14();
  void RL_fabric_rl_wr_resp_err_to_master();
  void RL_fabric_rl_wr_resp_err_to_master_1();
  void RL_fabric_rl_wr_resp_err_to_master_2();
  void RL_fabric_rl_rd_resp_slave_to_master();
  void RL_fabric_rl_rd_resp_slave_to_master_1();
  void RL_fabric_rl_rd_resp_slave_to_master_2();
  void RL_fabric_rl_rd_resp_slave_to_master_3();
  void RL_fabric_rl_rd_resp_slave_to_master_4();
  void RL_fabric_rl_rd_resp_slave_to_master_5();
  void RL_fabric_rl_rd_resp_slave_to_master_6();
  void RL_fabric_rl_rd_resp_slave_to_master_7();
  void RL_fabric_rl_rd_resp_slave_to_master_8();
  void RL_fabric_rl_rd_resp_slave_to_master_9();
  void RL_fabric_rl_rd_resp_slave_to_master_10();
  void RL_fabric_rl_rd_resp_slave_to_master_11();
  void RL_fabric_rl_rd_resp_slave_to_master_12();
  void RL_fabric_rl_rd_resp_slave_to_master_13();
  void RL_fabric_rl_rd_resp_slave_to_master_14();
  void RL_fabric_rl_rd_resp_err_to_master();
  void RL_fabric_rl_rd_resp_err_to_master_1();
  void RL_fabric_rl_rd_resp_err_to_master_2();
 
 /* Methods */
 public:
  tUInt8 METH_v_from_masters_0_m_buser();
  tUInt8 METH_RDY_v_from_masters_0_m_buser();
  tUInt8 METH_v_from_masters_0_m_ruser();
  tUInt8 METH_RDY_v_from_masters_0_m_ruser();
  tUInt8 METH_v_from_masters_1_m_buser();
  tUInt8 METH_RDY_v_from_masters_1_m_buser();
  tUInt8 METH_v_from_masters_1_m_ruser();
  tUInt8 METH_RDY_v_from_masters_1_m_ruser();
  tUInt8 METH_v_from_masters_2_m_buser();
  tUInt8 METH_RDY_v_from_masters_2_m_buser();
  tUInt8 METH_v_from_masters_2_m_ruser();
  tUInt8 METH_RDY_v_from_masters_2_m_ruser();
  tUInt8 METH_v_to_slaves_0_m_awuser();
  tUInt8 METH_RDY_v_to_slaves_0_m_awuser();
  tUInt8 METH_v_to_slaves_0_m_aruser();
  tUInt8 METH_RDY_v_to_slaves_0_m_aruser();
  tUInt8 METH_v_to_slaves_1_m_awuser();
  tUInt8 METH_RDY_v_to_slaves_1_m_awuser();
  tUInt8 METH_v_to_slaves_1_m_aruser();
  tUInt8 METH_RDY_v_to_slaves_1_m_aruser();
  tUInt8 METH_v_to_slaves_2_m_awuser();
  tUInt8 METH_RDY_v_to_slaves_2_m_awuser();
  tUInt8 METH_v_to_slaves_2_m_aruser();
  tUInt8 METH_RDY_v_to_slaves_2_m_aruser();
  tUInt8 METH_v_to_slaves_3_m_awuser();
  tUInt8 METH_RDY_v_to_slaves_3_m_awuser();
  tUInt8 METH_v_to_slaves_3_m_aruser();
  tUInt8 METH_RDY_v_to_slaves_3_m_aruser();
  tUInt8 METH_v_to_slaves_4_m_awuser();
  tUInt8 METH_RDY_v_to_slaves_4_m_awuser();
  tUInt8 METH_v_to_slaves_4_m_aruser();
  tUInt8 METH_RDY_v_to_slaves_4_m_aruser();
  void METH_reset();
  tUInt8 METH_RDY_reset();
  void METH_set_verbosity(tUInt8 ARG_set_verbosity_verbosity);
  tUInt8 METH_RDY_set_verbosity();
  void METH_v_from_masters_0_m_awvalid(tUInt8 ARG_v_from_masters_0_awvalid,
				       tUInt64 ARG_v_from_masters_0_awaddr,
				       tUInt8 ARG_v_from_masters_0_awprot,
				       tUInt8 ARG_v_from_masters_0_awuser);
  tUInt8 METH_RDY_v_from_masters_0_m_awvalid();
  tUInt8 METH_v_from_masters_0_m_awready();
  tUInt8 METH_RDY_v_from_masters_0_m_awready();
  void METH_v_from_masters_0_m_wvalid(tUInt8 ARG_v_from_masters_0_wvalid,
				      tUInt64 ARG_v_from_masters_0_wdata,
				      tUInt8 ARG_v_from_masters_0_wstrb);
  tUInt8 METH_RDY_v_from_masters_0_m_wvalid();
  tUInt8 METH_v_from_masters_0_m_wready();
  tUInt8 METH_RDY_v_from_masters_0_m_wready();
  tUInt8 METH_v_from_masters_0_m_bvalid();
  tUInt8 METH_RDY_v_from_masters_0_m_bvalid();
  tUInt8 METH_v_from_masters_0_m_bresp();
  tUInt8 METH_RDY_v_from_masters_0_m_bresp();
  void METH_v_from_masters_0_m_bready(tUInt8 ARG_v_from_masters_0_bready);
  tUInt8 METH_RDY_v_from_masters_0_m_bready();
  void METH_v_from_masters_0_m_arvalid(tUInt8 ARG_v_from_masters_0_arvalid,
				       tUInt64 ARG_v_from_masters_0_araddr,
				       tUInt8 ARG_v_from_masters_0_arprot,
				       tUInt8 ARG_v_from_masters_0_aruser);
  tUInt8 METH_RDY_v_from_masters_0_m_arvalid();
  tUInt8 METH_v_from_masters_0_m_arready();
  tUInt8 METH_RDY_v_from_masters_0_m_arready();
  tUInt8 METH_v_from_masters_0_m_rvalid();
  tUInt8 METH_RDY_v_from_masters_0_m_rvalid();
  tUInt8 METH_v_from_masters_0_m_rresp();
  tUInt8 METH_RDY_v_from_masters_0_m_rresp();
  tUInt64 METH_v_from_masters_0_m_rdata();
  tUInt8 METH_RDY_v_from_masters_0_m_rdata();
  void METH_v_from_masters_0_m_rready(tUInt8 ARG_v_from_masters_0_rready);
  tUInt8 METH_RDY_v_from_masters_0_m_rready();
  void METH_v_from_masters_1_m_awvalid(tUInt8 ARG_v_from_masters_1_awvalid,
				       tUInt64 ARG_v_from_masters_1_awaddr,
				       tUInt8 ARG_v_from_masters_1_awprot,
				       tUInt8 ARG_v_from_masters_1_awuser);
  tUInt8 METH_RDY_v_from_masters_1_m_awvalid();
  tUInt8 METH_v_from_masters_1_m_awready();
  tUInt8 METH_RDY_v_from_masters_1_m_awready();
  void METH_v_from_masters_1_m_wvalid(tUInt8 ARG_v_from_masters_1_wvalid,
				      tUInt64 ARG_v_from_masters_1_wdata,
				      tUInt8 ARG_v_from_masters_1_wstrb);
  tUInt8 METH_RDY_v_from_masters_1_m_wvalid();
  tUInt8 METH_v_from_masters_1_m_wready();
  tUInt8 METH_RDY_v_from_masters_1_m_wready();
  tUInt8 METH_v_from_masters_1_m_bvalid();
  tUInt8 METH_RDY_v_from_masters_1_m_bvalid();
  tUInt8 METH_v_from_masters_1_m_bresp();
  tUInt8 METH_RDY_v_from_masters_1_m_bresp();
  void METH_v_from_masters_1_m_bready(tUInt8 ARG_v_from_masters_1_bready);
  tUInt8 METH_RDY_v_from_masters_1_m_bready();
  void METH_v_from_masters_1_m_arvalid(tUInt8 ARG_v_from_masters_1_arvalid,
				       tUInt64 ARG_v_from_masters_1_araddr,
				       tUInt8 ARG_v_from_masters_1_arprot,
				       tUInt8 ARG_v_from_masters_1_aruser);
  tUInt8 METH_RDY_v_from_masters_1_m_arvalid();
  tUInt8 METH_v_from_masters_1_m_arready();
  tUInt8 METH_RDY_v_from_masters_1_m_arready();
  tUInt8 METH_v_from_masters_1_m_rvalid();
  tUInt8 METH_RDY_v_from_masters_1_m_rvalid();
  tUInt8 METH_v_from_masters_1_m_rresp();
  tUInt8 METH_RDY_v_from_masters_1_m_rresp();
  tUInt64 METH_v_from_masters_1_m_rdata();
  tUInt8 METH_RDY_v_from_masters_1_m_rdata();
  void METH_v_from_masters_1_m_rready(tUInt8 ARG_v_from_masters_1_rready);
  tUInt8 METH_RDY_v_from_masters_1_m_rready();
  void METH_v_from_masters_2_m_awvalid(tUInt8 ARG_v_from_masters_2_awvalid,
				       tUInt64 ARG_v_from_masters_2_awaddr,
				       tUInt8 ARG_v_from_masters_2_awprot,
				       tUInt8 ARG_v_from_masters_2_awuser);
  tUInt8 METH_RDY_v_from_masters_2_m_awvalid();
  tUInt8 METH_v_from_masters_2_m_awready();
  tUInt8 METH_RDY_v_from_masters_2_m_awready();
  void METH_v_from_masters_2_m_wvalid(tUInt8 ARG_v_from_masters_2_wvalid,
				      tUInt64 ARG_v_from_masters_2_wdata,
				      tUInt8 ARG_v_from_masters_2_wstrb);
  tUInt8 METH_RDY_v_from_masters_2_m_wvalid();
  tUInt8 METH_v_from_masters_2_m_wready();
  tUInt8 METH_RDY_v_from_masters_2_m_wready();
  tUInt8 METH_v_from_masters_2_m_bvalid();
  tUInt8 METH_RDY_v_from_masters_2_m_bvalid();
  tUInt8 METH_v_from_masters_2_m_bresp();
  tUInt8 METH_RDY_v_from_masters_2_m_bresp();
  void METH_v_from_masters_2_m_bready(tUInt8 ARG_v_from_masters_2_bready);
  tUInt8 METH_RDY_v_from_masters_2_m_bready();
  void METH_v_from_masters_2_m_arvalid(tUInt8 ARG_v_from_masters_2_arvalid,
				       tUInt64 ARG_v_from_masters_2_araddr,
				       tUInt8 ARG_v_from_masters_2_arprot,
				       tUInt8 ARG_v_from_masters_2_aruser);
  tUInt8 METH_RDY_v_from_masters_2_m_arvalid();
  tUInt8 METH_v_from_masters_2_m_arready();
  tUInt8 METH_RDY_v_from_masters_2_m_arready();
  tUInt8 METH_v_from_masters_2_m_rvalid();
  tUInt8 METH_RDY_v_from_masters_2_m_rvalid();
  tUInt8 METH_v_from_masters_2_m_rresp();
  tUInt8 METH_RDY_v_from_masters_2_m_rresp();
  tUInt64 METH_v_from_masters_2_m_rdata();
  tUInt8 METH_RDY_v_from_masters_2_m_rdata();
  void METH_v_from_masters_2_m_rready(tUInt8 ARG_v_from_masters_2_rready);
  tUInt8 METH_RDY_v_from_masters_2_m_rready();
  tUInt8 METH_v_to_slaves_0_m_awvalid();
  tUInt8 METH_RDY_v_to_slaves_0_m_awvalid();
  tUInt64 METH_v_to_slaves_0_m_awaddr();
  tUInt8 METH_RDY_v_to_slaves_0_m_awaddr();
  tUInt8 METH_v_to_slaves_0_m_awprot();
  tUInt8 METH_RDY_v_to_slaves_0_m_awprot();
  void METH_v_to_slaves_0_m_awready(tUInt8 ARG_v_to_slaves_0_awready);
  tUInt8 METH_RDY_v_to_slaves_0_m_awready();
  tUInt8 METH_v_to_slaves_0_m_wvalid();
  tUInt8 METH_RDY_v_to_slaves_0_m_wvalid();
  tUInt64 METH_v_to_slaves_0_m_wdata();
  tUInt8 METH_RDY_v_to_slaves_0_m_wdata();
  tUInt8 METH_v_to_slaves_0_m_wstrb();
  tUInt8 METH_RDY_v_to_slaves_0_m_wstrb();
  void METH_v_to_slaves_0_m_wready(tUInt8 ARG_v_to_slaves_0_wready);
  tUInt8 METH_RDY_v_to_slaves_0_m_wready();
  void METH_v_to_slaves_0_m_bvalid(tUInt8 ARG_v_to_slaves_0_bvalid,
				   tUInt8 ARG_v_to_slaves_0_bresp,
				   tUInt8 ARG_v_to_slaves_0_buser);
  tUInt8 METH_RDY_v_to_slaves_0_m_bvalid();
  tUInt8 METH_v_to_slaves_0_m_bready();
  tUInt8 METH_RDY_v_to_slaves_0_m_bready();
  tUInt8 METH_v_to_slaves_0_m_arvalid();
  tUInt8 METH_RDY_v_to_slaves_0_m_arvalid();
  tUInt64 METH_v_to_slaves_0_m_araddr();
  tUInt8 METH_RDY_v_to_slaves_0_m_araddr();
  tUInt8 METH_v_to_slaves_0_m_arprot();
  tUInt8 METH_RDY_v_to_slaves_0_m_arprot();
  void METH_v_to_slaves_0_m_arready(tUInt8 ARG_v_to_slaves_0_arready);
  tUInt8 METH_RDY_v_to_slaves_0_m_arready();
  void METH_v_to_slaves_0_m_rvalid(tUInt8 ARG_v_to_slaves_0_rvalid,
				   tUInt8 ARG_v_to_slaves_0_rresp,
				   tUInt64 ARG_v_to_slaves_0_rdata,
				   tUInt8 ARG_v_to_slaves_0_ruser);
  tUInt8 METH_RDY_v_to_slaves_0_m_rvalid();
  tUInt8 METH_v_to_slaves_0_m_rready();
  tUInt8 METH_RDY_v_to_slaves_0_m_rready();
  tUInt8 METH_v_to_slaves_1_m_awvalid();
  tUInt8 METH_RDY_v_to_slaves_1_m_awvalid();
  tUInt64 METH_v_to_slaves_1_m_awaddr();
  tUInt8 METH_RDY_v_to_slaves_1_m_awaddr();
  tUInt8 METH_v_to_slaves_1_m_awprot();
  tUInt8 METH_RDY_v_to_slaves_1_m_awprot();
  void METH_v_to_slaves_1_m_awready(tUInt8 ARG_v_to_slaves_1_awready);
  tUInt8 METH_RDY_v_to_slaves_1_m_awready();
  tUInt8 METH_v_to_slaves_1_m_wvalid();
  tUInt8 METH_RDY_v_to_slaves_1_m_wvalid();
  tUInt64 METH_v_to_slaves_1_m_wdata();
  tUInt8 METH_RDY_v_to_slaves_1_m_wdata();
  tUInt8 METH_v_to_slaves_1_m_wstrb();
  tUInt8 METH_RDY_v_to_slaves_1_m_wstrb();
  void METH_v_to_slaves_1_m_wready(tUInt8 ARG_v_to_slaves_1_wready);
  tUInt8 METH_RDY_v_to_slaves_1_m_wready();
  void METH_v_to_slaves_1_m_bvalid(tUInt8 ARG_v_to_slaves_1_bvalid,
				   tUInt8 ARG_v_to_slaves_1_bresp,
				   tUInt8 ARG_v_to_slaves_1_buser);
  tUInt8 METH_RDY_v_to_slaves_1_m_bvalid();
  tUInt8 METH_v_to_slaves_1_m_bready();
  tUInt8 METH_RDY_v_to_slaves_1_m_bready();
  tUInt8 METH_v_to_slaves_1_m_arvalid();
  tUInt8 METH_RDY_v_to_slaves_1_m_arvalid();
  tUInt64 METH_v_to_slaves_1_m_araddr();
  tUInt8 METH_RDY_v_to_slaves_1_m_araddr();
  tUInt8 METH_v_to_slaves_1_m_arprot();
  tUInt8 METH_RDY_v_to_slaves_1_m_arprot();
  void METH_v_to_slaves_1_m_arready(tUInt8 ARG_v_to_slaves_1_arready);
  tUInt8 METH_RDY_v_to_slaves_1_m_arready();
  void METH_v_to_slaves_1_m_rvalid(tUInt8 ARG_v_to_slaves_1_rvalid,
				   tUInt8 ARG_v_to_slaves_1_rresp,
				   tUInt64 ARG_v_to_slaves_1_rdata,
				   tUInt8 ARG_v_to_slaves_1_ruser);
  tUInt8 METH_RDY_v_to_slaves_1_m_rvalid();
  tUInt8 METH_v_to_slaves_1_m_rready();
  tUInt8 METH_RDY_v_to_slaves_1_m_rready();
  tUInt8 METH_v_to_slaves_2_m_awvalid();
  tUInt8 METH_RDY_v_to_slaves_2_m_awvalid();
  tUInt64 METH_v_to_slaves_2_m_awaddr();
  tUInt8 METH_RDY_v_to_slaves_2_m_awaddr();
  tUInt8 METH_v_to_slaves_2_m_awprot();
  tUInt8 METH_RDY_v_to_slaves_2_m_awprot();
  void METH_v_to_slaves_2_m_awready(tUInt8 ARG_v_to_slaves_2_awready);
  tUInt8 METH_RDY_v_to_slaves_2_m_awready();
  tUInt8 METH_v_to_slaves_2_m_wvalid();
  tUInt8 METH_RDY_v_to_slaves_2_m_wvalid();
  tUInt64 METH_v_to_slaves_2_m_wdata();
  tUInt8 METH_RDY_v_to_slaves_2_m_wdata();
  tUInt8 METH_v_to_slaves_2_m_wstrb();
  tUInt8 METH_RDY_v_to_slaves_2_m_wstrb();
  void METH_v_to_slaves_2_m_wready(tUInt8 ARG_v_to_slaves_2_wready);
  tUInt8 METH_RDY_v_to_slaves_2_m_wready();
  void METH_v_to_slaves_2_m_bvalid(tUInt8 ARG_v_to_slaves_2_bvalid,
				   tUInt8 ARG_v_to_slaves_2_bresp,
				   tUInt8 ARG_v_to_slaves_2_buser);
  tUInt8 METH_RDY_v_to_slaves_2_m_bvalid();
  tUInt8 METH_v_to_slaves_2_m_bready();
  tUInt8 METH_RDY_v_to_slaves_2_m_bready();
  tUInt8 METH_v_to_slaves_2_m_arvalid();
  tUInt8 METH_RDY_v_to_slaves_2_m_arvalid();
  tUInt64 METH_v_to_slaves_2_m_araddr();
  tUInt8 METH_RDY_v_to_slaves_2_m_araddr();
  tUInt8 METH_v_to_slaves_2_m_arprot();
  tUInt8 METH_RDY_v_to_slaves_2_m_arprot();
  void METH_v_to_slaves_2_m_arready(tUInt8 ARG_v_to_slaves_2_arready);
  tUInt8 METH_RDY_v_to_slaves_2_m_arready();
  void METH_v_to_slaves_2_m_rvalid(tUInt8 ARG_v_to_slaves_2_rvalid,
				   tUInt8 ARG_v_to_slaves_2_rresp,
				   tUInt64 ARG_v_to_slaves_2_rdata,
				   tUInt8 ARG_v_to_slaves_2_ruser);
  tUInt8 METH_RDY_v_to_slaves_2_m_rvalid();
  tUInt8 METH_v_to_slaves_2_m_rready();
  tUInt8 METH_RDY_v_to_slaves_2_m_rready();
  tUInt8 METH_v_to_slaves_3_m_awvalid();
  tUInt8 METH_RDY_v_to_slaves_3_m_awvalid();
  tUInt64 METH_v_to_slaves_3_m_awaddr();
  tUInt8 METH_RDY_v_to_slaves_3_m_awaddr();
  tUInt8 METH_v_to_slaves_3_m_awprot();
  tUInt8 METH_RDY_v_to_slaves_3_m_awprot();
  void METH_v_to_slaves_3_m_awready(tUInt8 ARG_v_to_slaves_3_awready);
  tUInt8 METH_RDY_v_to_slaves_3_m_awready();
  tUInt8 METH_v_to_slaves_3_m_wvalid();
  tUInt8 METH_RDY_v_to_slaves_3_m_wvalid();
  tUInt64 METH_v_to_slaves_3_m_wdata();
  tUInt8 METH_RDY_v_to_slaves_3_m_wdata();
  tUInt8 METH_v_to_slaves_3_m_wstrb();
  tUInt8 METH_RDY_v_to_slaves_3_m_wstrb();
  void METH_v_to_slaves_3_m_wready(tUInt8 ARG_v_to_slaves_3_wready);
  tUInt8 METH_RDY_v_to_slaves_3_m_wready();
  void METH_v_to_slaves_3_m_bvalid(tUInt8 ARG_v_to_slaves_3_bvalid,
				   tUInt8 ARG_v_to_slaves_3_bresp,
				   tUInt8 ARG_v_to_slaves_3_buser);
  tUInt8 METH_RDY_v_to_slaves_3_m_bvalid();
  tUInt8 METH_v_to_slaves_3_m_bready();
  tUInt8 METH_RDY_v_to_slaves_3_m_bready();
  tUInt8 METH_v_to_slaves_3_m_arvalid();
  tUInt8 METH_RDY_v_to_slaves_3_m_arvalid();
  tUInt64 METH_v_to_slaves_3_m_araddr();
  tUInt8 METH_RDY_v_to_slaves_3_m_araddr();
  tUInt8 METH_v_to_slaves_3_m_arprot();
  tUInt8 METH_RDY_v_to_slaves_3_m_arprot();
  void METH_v_to_slaves_3_m_arready(tUInt8 ARG_v_to_slaves_3_arready);
  tUInt8 METH_RDY_v_to_slaves_3_m_arready();
  void METH_v_to_slaves_3_m_rvalid(tUInt8 ARG_v_to_slaves_3_rvalid,
				   tUInt8 ARG_v_to_slaves_3_rresp,
				   tUInt64 ARG_v_to_slaves_3_rdata,
				   tUInt8 ARG_v_to_slaves_3_ruser);
  tUInt8 METH_RDY_v_to_slaves_3_m_rvalid();
  tUInt8 METH_v_to_slaves_3_m_rready();
  tUInt8 METH_RDY_v_to_slaves_3_m_rready();
  tUInt8 METH_v_to_slaves_4_m_awvalid();
  tUInt8 METH_RDY_v_to_slaves_4_m_awvalid();
  tUInt64 METH_v_to_slaves_4_m_awaddr();
  tUInt8 METH_RDY_v_to_slaves_4_m_awaddr();
  tUInt8 METH_v_to_slaves_4_m_awprot();
  tUInt8 METH_RDY_v_to_slaves_4_m_awprot();
  void METH_v_to_slaves_4_m_awready(tUInt8 ARG_v_to_slaves_4_awready);
  tUInt8 METH_RDY_v_to_slaves_4_m_awready();
  tUInt8 METH_v_to_slaves_4_m_wvalid();
  tUInt8 METH_RDY_v_to_slaves_4_m_wvalid();
  tUInt64 METH_v_to_slaves_4_m_wdata();
  tUInt8 METH_RDY_v_to_slaves_4_m_wdata();
  tUInt8 METH_v_to_slaves_4_m_wstrb();
  tUInt8 METH_RDY_v_to_slaves_4_m_wstrb();
  void METH_v_to_slaves_4_m_wready(tUInt8 ARG_v_to_slaves_4_wready);
  tUInt8 METH_RDY_v_to_slaves_4_m_wready();
  void METH_v_to_slaves_4_m_bvalid(tUInt8 ARG_v_to_slaves_4_bvalid,
				   tUInt8 ARG_v_to_slaves_4_bresp,
				   tUInt8 ARG_v_to_slaves_4_buser);
  tUInt8 METH_RDY_v_to_slaves_4_m_bvalid();
  tUInt8 METH_v_to_slaves_4_m_bready();
  tUInt8 METH_RDY_v_to_slaves_4_m_bready();
  tUInt8 METH_v_to_slaves_4_m_arvalid();
  tUInt8 METH_RDY_v_to_slaves_4_m_arvalid();
  tUInt64 METH_v_to_slaves_4_m_araddr();
  tUInt8 METH_RDY_v_to_slaves_4_m_araddr();
  tUInt8 METH_v_to_slaves_4_m_arprot();
  tUInt8 METH_RDY_v_to_slaves_4_m_arprot();
  void METH_v_to_slaves_4_m_arready(tUInt8 ARG_v_to_slaves_4_arready);
  tUInt8 METH_RDY_v_to_slaves_4_m_arready();
  void METH_v_to_slaves_4_m_rvalid(tUInt8 ARG_v_to_slaves_4_rvalid,
				   tUInt8 ARG_v_to_slaves_4_rresp,
				   tUInt64 ARG_v_to_slaves_4_rdata,
				   tUInt8 ARG_v_to_slaves_4_ruser);
  tUInt8 METH_RDY_v_to_slaves_4_m_rvalid();
  tUInt8 METH_v_to_slaves_4_m_rready();
  tUInt8 METH_RDY_v_to_slaves_4_m_rready();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkFabric &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkFabric &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkFabric &backing);
  void vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkFabric &backing);
};

#endif /* ifndef __mkFabric_h__ */
