/*
 * Generated by Bluespec Compiler, version 2017.07.A (build 1da80f1, 2017-07-21)
 * 
 * On Wed Aug 15 16:00:33 BST 2018
 * 
 */
#include "bluesim_primitives.h"
#include "mkSoC_Top.h"


/* Constructor */
MOD_mkSoC_Top::MOD_mkSoC_Top(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_boot_rom(simHdl, "boot_rom", this),
    INST_brvf_core(simHdl, "brvf_core", this, 2147483648llu),
    INST_fabric(simHdl, "fabric", this),
    INST_mem0_controller(simHdl, "mem0_controller", this),
    INST_rg_state(simHdl, "rg_state", this, 2u, (tUInt8)0u, (tUInt8)0u),
    INST_soc_map(simHdl, "soc_map", this),
    INST_timer0(simHdl, "timer0", this),
    INST_uart0(simHdl, "uart0", this),
    PORT_RST_N((tUInt8)1u)
{
  PORT_to_raw_mem_response_put.setSize(256u);
  PORT_to_raw_mem_response_put.clear();
  PORT_to_raw_mem_request_get.setSize(353u);
  PORT_to_raw_mem_request_get.clear();
  symbol_count = 54u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkSoC_Top::init_symbols_0()
{
  init_symbol(&symbols[0u], "boot_rom", SYM_MODULE, &INST_boot_rom);
  init_symbol(&symbols[1u], "brvf_core", SYM_MODULE, &INST_brvf_core);
  init_symbol(&symbols[2u], "fabric", SYM_MODULE, &INST_fabric);
  init_symbol(&symbols[3u], "mem0_controller", SYM_MODULE, &INST_mem0_controller);
  init_symbol(&symbols[4u], "RL_rl_connect_software_interrupt_request", SYM_RULE);
  init_symbol(&symbols[5u], "RL_rl_connect_timer_interrupt_request", SYM_RULE);
  init_symbol(&symbols[6u], "RL_rl_rd_addr_channel", SYM_RULE);
  init_symbol(&symbols[7u], "RL_rl_rd_addr_channel_1", SYM_RULE);
  init_symbol(&symbols[8u], "RL_rl_rd_addr_channel_2", SYM_RULE);
  init_symbol(&symbols[9u], "RL_rl_rd_addr_channel_3", SYM_RULE);
  init_symbol(&symbols[10u], "RL_rl_rd_addr_channel_4", SYM_RULE);
  init_symbol(&symbols[11u], "RL_rl_rd_addr_channel_5", SYM_RULE);
  init_symbol(&symbols[12u], "RL_rl_rd_addr_channel_6", SYM_RULE);
  init_symbol(&symbols[13u], "RL_rl_rd_addr_channel_7", SYM_RULE);
  init_symbol(&symbols[14u], "RL_rl_rd_data_channel", SYM_RULE);
  init_symbol(&symbols[15u], "RL_rl_rd_data_channel_1", SYM_RULE);
  init_symbol(&symbols[16u], "RL_rl_rd_data_channel_2", SYM_RULE);
  init_symbol(&symbols[17u], "RL_rl_rd_data_channel_3", SYM_RULE);
  init_symbol(&symbols[18u], "RL_rl_rd_data_channel_4", SYM_RULE);
  init_symbol(&symbols[19u], "RL_rl_rd_data_channel_5", SYM_RULE);
  init_symbol(&symbols[20u], "RL_rl_rd_data_channel_6", SYM_RULE);
  init_symbol(&symbols[21u], "RL_rl_rd_data_channel_7", SYM_RULE);
  init_symbol(&symbols[22u], "RL_rl_reset_complete", SYM_RULE);
  init_symbol(&symbols[23u], "RL_rl_reset_start_2", SYM_RULE);
  init_symbol(&symbols[24u], "RL_rl_wr_addr_channel", SYM_RULE);
  init_symbol(&symbols[25u], "RL_rl_wr_addr_channel_1", SYM_RULE);
  init_symbol(&symbols[26u], "RL_rl_wr_addr_channel_2", SYM_RULE);
  init_symbol(&symbols[27u], "RL_rl_wr_addr_channel_3", SYM_RULE);
  init_symbol(&symbols[28u], "RL_rl_wr_addr_channel_4", SYM_RULE);
  init_symbol(&symbols[29u], "RL_rl_wr_addr_channel_5", SYM_RULE);
  init_symbol(&symbols[30u], "RL_rl_wr_addr_channel_6", SYM_RULE);
  init_symbol(&symbols[31u], "RL_rl_wr_addr_channel_7", SYM_RULE);
  init_symbol(&symbols[32u], "RL_rl_wr_data_channel", SYM_RULE);
  init_symbol(&symbols[33u], "RL_rl_wr_data_channel_1", SYM_RULE);
  init_symbol(&symbols[34u], "RL_rl_wr_data_channel_2", SYM_RULE);
  init_symbol(&symbols[35u], "RL_rl_wr_data_channel_3", SYM_RULE);
  init_symbol(&symbols[36u], "RL_rl_wr_data_channel_4", SYM_RULE);
  init_symbol(&symbols[37u], "RL_rl_wr_data_channel_5", SYM_RULE);
  init_symbol(&symbols[38u], "RL_rl_wr_data_channel_6", SYM_RULE);
  init_symbol(&symbols[39u], "RL_rl_wr_data_channel_7", SYM_RULE);
  init_symbol(&symbols[40u], "RL_rl_wr_response_channel", SYM_RULE);
  init_symbol(&symbols[41u], "RL_rl_wr_response_channel_1", SYM_RULE);
  init_symbol(&symbols[42u], "RL_rl_wr_response_channel_2", SYM_RULE);
  init_symbol(&symbols[43u], "RL_rl_wr_response_channel_3", SYM_RULE);
  init_symbol(&symbols[44u], "RL_rl_wr_response_channel_4", SYM_RULE);
  init_symbol(&symbols[45u], "RL_rl_wr_response_channel_5", SYM_RULE);
  init_symbol(&symbols[46u], "RL_rl_wr_response_channel_6", SYM_RULE);
  init_symbol(&symbols[47u], "RL_rl_wr_response_channel_7", SYM_RULE);
  init_symbol(&symbols[48u], "rg_state", SYM_MODULE, &INST_rg_state);
  init_symbol(&symbols[49u], "soc_map", SYM_MODULE, &INST_soc_map);
  init_symbol(&symbols[50u], "timer0", SYM_MODULE, &INST_timer0);
  init_symbol(&symbols[51u], "to_raw_mem_request_get", SYM_PORT, &PORT_to_raw_mem_request_get, 353u);
  init_symbol(&symbols[52u],
	      "to_raw_mem_response_put",
	      SYM_PORT,
	      &PORT_to_raw_mem_response_put,
	      256u);
  init_symbol(&symbols[53u], "uart0", SYM_MODULE, &INST_uart0);
}


/* Rule actions */

void MOD_mkSoC_Top::RL_rl_wr_addr_channel()
{
  tUInt8 DEF_awuser__h3479;
  tUInt8 DEF_brvf_core_cpu_imem_master_m_awvalid____d1;
  tUInt8 DEF_fabric_v_from_masters_1_m_awready____d5;
  tUInt8 DEF_awprot__h3478;
  tUInt64 DEF_awaddr__h3477;
  DEF_awaddr__h3477 = INST_brvf_core.METH_cpu_imem_master_m_awaddr();
  DEF_awprot__h3478 = INST_brvf_core.METH_cpu_imem_master_m_awprot();
  DEF_fabric_v_from_masters_1_m_awready____d5 = INST_fabric.METH_v_from_masters_1_m_awready();
  DEF_brvf_core_cpu_imem_master_m_awvalid____d1 = INST_brvf_core.METH_cpu_imem_master_m_awvalid();
  DEF_awuser__h3479 = INST_brvf_core.METH_cpu_imem_master_m_awuser();
  INST_fabric.METH_v_from_masters_1_m_awvalid(DEF_brvf_core_cpu_imem_master_m_awvalid____d1,
					      DEF_awaddr__h3477,
					      DEF_awprot__h3478,
					      DEF_awuser__h3479);
  INST_brvf_core.METH_cpu_imem_master_m_awready(DEF_fabric_v_from_masters_1_m_awready____d5);
}

void MOD_mkSoC_Top::RL_rl_wr_data_channel()
{
  tUInt8 DEF_brvf_core_cpu_imem_master_m_wvalid____d6;
  tUInt8 DEF_fabric_v_from_masters_1_m_wready____d9;
  tUInt8 DEF_wstrb__h3564;
  tUInt64 DEF_wdata__h3563;
  DEF_wdata__h3563 = INST_brvf_core.METH_cpu_imem_master_m_wdata();
  DEF_wstrb__h3564 = INST_brvf_core.METH_cpu_imem_master_m_wstrb();
  DEF_fabric_v_from_masters_1_m_wready____d9 = INST_fabric.METH_v_from_masters_1_m_wready();
  DEF_brvf_core_cpu_imem_master_m_wvalid____d6 = INST_brvf_core.METH_cpu_imem_master_m_wvalid();
  INST_fabric.METH_v_from_masters_1_m_wvalid(DEF_brvf_core_cpu_imem_master_m_wvalid____d6,
					     DEF_wdata__h3563,
					     DEF_wstrb__h3564);
  INST_brvf_core.METH_cpu_imem_master_m_wready(DEF_fabric_v_from_masters_1_m_wready____d9);
}

void MOD_mkSoC_Top::RL_rl_wr_response_channel()
{
  tUInt8 DEF_buser__h3621;
  tUInt8 DEF_brvf_core_cpu_imem_master_m_bready____d13;
  tUInt8 DEF_fabric_v_from_masters_1_m_bvalid____d10;
  tUInt8 DEF_bresp__h3620;
  DEF_bresp__h3620 = INST_fabric.METH_v_from_masters_1_m_bresp();
  DEF_fabric_v_from_masters_1_m_bvalid____d10 = INST_fabric.METH_v_from_masters_1_m_bvalid();
  DEF_brvf_core_cpu_imem_master_m_bready____d13 = INST_brvf_core.METH_cpu_imem_master_m_bready();
  DEF_buser__h3621 = INST_fabric.METH_v_from_masters_1_m_buser();
  INST_brvf_core.METH_cpu_imem_master_m_bvalid(DEF_fabric_v_from_masters_1_m_bvalid____d10,
					       DEF_bresp__h3620,
					       DEF_buser__h3621);
  INST_fabric.METH_v_from_masters_1_m_bready(DEF_brvf_core_cpu_imem_master_m_bready____d13);
}

void MOD_mkSoC_Top::RL_rl_rd_addr_channel()
{
  tUInt8 DEF_aruser__h3680;
  tUInt8 DEF_brvf_core_cpu_imem_master_m_arvalid____d14;
  tUInt8 DEF_fabric_v_from_masters_1_m_arready____d18;
  tUInt8 DEF_arprot__h3679;
  tUInt64 DEF_araddr__h3678;
  DEF_araddr__h3678 = INST_brvf_core.METH_cpu_imem_master_m_araddr();
  DEF_arprot__h3679 = INST_brvf_core.METH_cpu_imem_master_m_arprot();
  DEF_fabric_v_from_masters_1_m_arready____d18 = INST_fabric.METH_v_from_masters_1_m_arready();
  DEF_brvf_core_cpu_imem_master_m_arvalid____d14 = INST_brvf_core.METH_cpu_imem_master_m_arvalid();
  DEF_aruser__h3680 = INST_brvf_core.METH_cpu_imem_master_m_aruser();
  INST_fabric.METH_v_from_masters_1_m_arvalid(DEF_brvf_core_cpu_imem_master_m_arvalid____d14,
					      DEF_araddr__h3678,
					      DEF_arprot__h3679,
					      DEF_aruser__h3680);
  INST_brvf_core.METH_cpu_imem_master_m_arready(DEF_fabric_v_from_masters_1_m_arready____d18);
}

void MOD_mkSoC_Top::RL_rl_rd_data_channel()
{
  tUInt8 DEF_ruser__h3743;
  tUInt8 DEF_brvf_core_cpu_imem_master_m_rready____d23;
  tUInt8 DEF_fabric_v_from_masters_1_m_rvalid____d19;
  tUInt8 DEF_rresp__h3741;
  tUInt64 DEF_rdata__h3742;
  DEF_rdata__h3742 = INST_fabric.METH_v_from_masters_1_m_rdata();
  DEF_rresp__h3741 = INST_fabric.METH_v_from_masters_1_m_rresp();
  DEF_fabric_v_from_masters_1_m_rvalid____d19 = INST_fabric.METH_v_from_masters_1_m_rvalid();
  DEF_brvf_core_cpu_imem_master_m_rready____d23 = INST_brvf_core.METH_cpu_imem_master_m_rready();
  DEF_ruser__h3743 = INST_fabric.METH_v_from_masters_1_m_ruser();
  INST_brvf_core.METH_cpu_imem_master_m_rvalid(DEF_fabric_v_from_masters_1_m_rvalid____d19,
					       DEF_rresp__h3741,
					       DEF_rdata__h3742,
					       DEF_ruser__h3743);
  INST_fabric.METH_v_from_masters_1_m_rready(DEF_brvf_core_cpu_imem_master_m_rready____d23);
}

void MOD_mkSoC_Top::RL_rl_wr_addr_channel_1()
{
  tUInt8 DEF_awuser__h3867;
  tUInt8 DEF_brvf_core_cpu_dmem_master_m_awvalid____d24;
  tUInt8 DEF_fabric_v_from_masters_2_m_awready____d28;
  tUInt8 DEF_awprot__h3866;
  tUInt64 DEF_awaddr__h3865;
  DEF_awaddr__h3865 = INST_brvf_core.METH_cpu_dmem_master_m_awaddr();
  DEF_awprot__h3866 = INST_brvf_core.METH_cpu_dmem_master_m_awprot();
  DEF_fabric_v_from_masters_2_m_awready____d28 = INST_fabric.METH_v_from_masters_2_m_awready();
  DEF_brvf_core_cpu_dmem_master_m_awvalid____d24 = INST_brvf_core.METH_cpu_dmem_master_m_awvalid();
  DEF_awuser__h3867 = INST_brvf_core.METH_cpu_dmem_master_m_awuser();
  INST_fabric.METH_v_from_masters_2_m_awvalid(DEF_brvf_core_cpu_dmem_master_m_awvalid____d24,
					      DEF_awaddr__h3865,
					      DEF_awprot__h3866,
					      DEF_awuser__h3867);
  INST_brvf_core.METH_cpu_dmem_master_m_awready(DEF_fabric_v_from_masters_2_m_awready____d28);
}

void MOD_mkSoC_Top::RL_rl_wr_data_channel_1()
{
  tUInt8 DEF_brvf_core_cpu_dmem_master_m_wvalid____d29;
  tUInt8 DEF_fabric_v_from_masters_2_m_wready____d32;
  tUInt8 DEF_wstrb__h3948;
  tUInt64 DEF_wdata__h3947;
  DEF_wdata__h3947 = INST_brvf_core.METH_cpu_dmem_master_m_wdata();
  DEF_wstrb__h3948 = INST_brvf_core.METH_cpu_dmem_master_m_wstrb();
  DEF_fabric_v_from_masters_2_m_wready____d32 = INST_fabric.METH_v_from_masters_2_m_wready();
  DEF_brvf_core_cpu_dmem_master_m_wvalid____d29 = INST_brvf_core.METH_cpu_dmem_master_m_wvalid();
  INST_fabric.METH_v_from_masters_2_m_wvalid(DEF_brvf_core_cpu_dmem_master_m_wvalid____d29,
					     DEF_wdata__h3947,
					     DEF_wstrb__h3948);
  INST_brvf_core.METH_cpu_dmem_master_m_wready(DEF_fabric_v_from_masters_2_m_wready____d32);
}

void MOD_mkSoC_Top::RL_rl_wr_response_channel_1()
{
  tUInt8 DEF_buser__h4005;
  tUInt8 DEF_brvf_core_cpu_dmem_master_m_bready____d36;
  tUInt8 DEF_fabric_v_from_masters_2_m_bvalid____d33;
  tUInt8 DEF_bresp__h4004;
  DEF_bresp__h4004 = INST_fabric.METH_v_from_masters_2_m_bresp();
  DEF_fabric_v_from_masters_2_m_bvalid____d33 = INST_fabric.METH_v_from_masters_2_m_bvalid();
  DEF_brvf_core_cpu_dmem_master_m_bready____d36 = INST_brvf_core.METH_cpu_dmem_master_m_bready();
  DEF_buser__h4005 = INST_fabric.METH_v_from_masters_2_m_buser();
  INST_brvf_core.METH_cpu_dmem_master_m_bvalid(DEF_fabric_v_from_masters_2_m_bvalid____d33,
					       DEF_bresp__h4004,
					       DEF_buser__h4005);
  INST_fabric.METH_v_from_masters_2_m_bready(DEF_brvf_core_cpu_dmem_master_m_bready____d36);
}

void MOD_mkSoC_Top::RL_rl_rd_addr_channel_1()
{
  tUInt8 DEF_aruser__h4064;
  tUInt8 DEF_brvf_core_cpu_dmem_master_m_arvalid____d37;
  tUInt8 DEF_fabric_v_from_masters_2_m_arready____d41;
  tUInt8 DEF_arprot__h4063;
  tUInt64 DEF_araddr__h4062;
  DEF_araddr__h4062 = INST_brvf_core.METH_cpu_dmem_master_m_araddr();
  DEF_arprot__h4063 = INST_brvf_core.METH_cpu_dmem_master_m_arprot();
  DEF_fabric_v_from_masters_2_m_arready____d41 = INST_fabric.METH_v_from_masters_2_m_arready();
  DEF_brvf_core_cpu_dmem_master_m_arvalid____d37 = INST_brvf_core.METH_cpu_dmem_master_m_arvalid();
  DEF_aruser__h4064 = INST_brvf_core.METH_cpu_dmem_master_m_aruser();
  INST_fabric.METH_v_from_masters_2_m_arvalid(DEF_brvf_core_cpu_dmem_master_m_arvalid____d37,
					      DEF_araddr__h4062,
					      DEF_arprot__h4063,
					      DEF_aruser__h4064);
  INST_brvf_core.METH_cpu_dmem_master_m_arready(DEF_fabric_v_from_masters_2_m_arready____d41);
}

void MOD_mkSoC_Top::RL_rl_rd_data_channel_1()
{
  tUInt8 DEF_ruser__h4127;
  tUInt8 DEF_brvf_core_cpu_dmem_master_m_rready____d46;
  tUInt8 DEF_fabric_v_from_masters_2_m_rvalid____d42;
  tUInt8 DEF_rresp__h4125;
  tUInt64 DEF_rdata__h4126;
  DEF_rdata__h4126 = INST_fabric.METH_v_from_masters_2_m_rdata();
  DEF_rresp__h4125 = INST_fabric.METH_v_from_masters_2_m_rresp();
  DEF_fabric_v_from_masters_2_m_rvalid____d42 = INST_fabric.METH_v_from_masters_2_m_rvalid();
  DEF_brvf_core_cpu_dmem_master_m_rready____d46 = INST_brvf_core.METH_cpu_dmem_master_m_rready();
  DEF_ruser__h4127 = INST_fabric.METH_v_from_masters_2_m_ruser();
  INST_brvf_core.METH_cpu_dmem_master_m_rvalid(DEF_fabric_v_from_masters_2_m_rvalid____d42,
					       DEF_rresp__h4125,
					       DEF_rdata__h4126,
					       DEF_ruser__h4127);
  INST_fabric.METH_v_from_masters_2_m_rready(DEF_brvf_core_cpu_dmem_master_m_rready____d46);
}

void MOD_mkSoC_Top::RL_rl_wr_addr_channel_2()
{
  INST_fabric.METH_v_from_masters_0_m_awvalid((tUInt8)0u,
					      12297829382473034410llu,
					      (tUInt8)2u,
					      (tUInt8)0u);
}

void MOD_mkSoC_Top::RL_rl_wr_data_channel_2()
{
  INST_fabric.METH_v_from_masters_0_m_wvalid((tUInt8)0u, 12297829382473034410llu, (tUInt8)170u);
}

void MOD_mkSoC_Top::RL_rl_wr_response_channel_2()
{
  INST_fabric.METH_v_from_masters_0_m_bready((tUInt8)0u);
}

void MOD_mkSoC_Top::RL_rl_rd_addr_channel_2()
{
  INST_fabric.METH_v_from_masters_0_m_arvalid((tUInt8)0u,
					      12297829382473034410llu,
					      (tUInt8)2u,
					      (tUInt8)0u);
}

void MOD_mkSoC_Top::RL_rl_rd_data_channel_2()
{
  INST_fabric.METH_v_from_masters_0_m_rready((tUInt8)0u);
}

void MOD_mkSoC_Top::RL_rl_wr_addr_channel_3()
{
  tUInt8 DEF_awuser__h4556;
  tUInt8 DEF_fabric_v_to_slaves_1_m_awvalid____d47;
  tUInt8 DEF_boot_rom_slave_m_awready____d51;
  tUInt8 DEF_awprot__h4555;
  tUInt64 DEF_awaddr__h4554;
  DEF_awaddr__h4554 = INST_fabric.METH_v_to_slaves_1_m_awaddr();
  DEF_awprot__h4555 = INST_fabric.METH_v_to_slaves_1_m_awprot();
  DEF_boot_rom_slave_m_awready____d51 = INST_boot_rom.METH_slave_m_awready();
  DEF_fabric_v_to_slaves_1_m_awvalid____d47 = INST_fabric.METH_v_to_slaves_1_m_awvalid();
  DEF_awuser__h4556 = INST_fabric.METH_v_to_slaves_1_m_awuser();
  INST_boot_rom.METH_slave_m_awvalid(DEF_fabric_v_to_slaves_1_m_awvalid____d47,
				     DEF_awaddr__h4554,
				     DEF_awprot__h4555,
				     DEF_awuser__h4556);
  INST_fabric.METH_v_to_slaves_1_m_awready(DEF_boot_rom_slave_m_awready____d51);
}

void MOD_mkSoC_Top::RL_rl_wr_data_channel_3()
{
  tUInt8 DEF_fabric_v_to_slaves_1_m_wvalid____d52;
  tUInt8 DEF_boot_rom_slave_m_wready____d55;
  tUInt8 DEF_wstrb__h4830;
  tUInt64 DEF_wdata__h4829;
  DEF_wdata__h4829 = INST_fabric.METH_v_to_slaves_1_m_wdata();
  DEF_wstrb__h4830 = INST_fabric.METH_v_to_slaves_1_m_wstrb();
  DEF_boot_rom_slave_m_wready____d55 = INST_boot_rom.METH_slave_m_wready();
  DEF_fabric_v_to_slaves_1_m_wvalid____d52 = INST_fabric.METH_v_to_slaves_1_m_wvalid();
  INST_boot_rom.METH_slave_m_wvalid(DEF_fabric_v_to_slaves_1_m_wvalid____d52,
				    DEF_wdata__h4829,
				    DEF_wstrb__h4830);
  INST_fabric.METH_v_to_slaves_1_m_wready(DEF_boot_rom_slave_m_wready____d55);
}

void MOD_mkSoC_Top::RL_rl_wr_response_channel_3()
{
  tUInt8 DEF_buser__h4887;
  tUInt8 DEF_fabric_v_to_slaves_1_m_bready____d59;
  tUInt8 DEF_boot_rom_slave_m_bvalid____d56;
  tUInt8 DEF_bresp__h4886;
  DEF_bresp__h4886 = INST_boot_rom.METH_slave_m_bresp();
  DEF_boot_rom_slave_m_bvalid____d56 = INST_boot_rom.METH_slave_m_bvalid();
  DEF_fabric_v_to_slaves_1_m_bready____d59 = INST_fabric.METH_v_to_slaves_1_m_bready();
  DEF_buser__h4887 = INST_boot_rom.METH_slave_m_buser();
  INST_fabric.METH_v_to_slaves_1_m_bvalid(DEF_boot_rom_slave_m_bvalid____d56,
					  DEF_bresp__h4886,
					  DEF_buser__h4887);
  INST_boot_rom.METH_slave_m_bready(DEF_fabric_v_to_slaves_1_m_bready____d59);
}

void MOD_mkSoC_Top::RL_rl_rd_addr_channel_3()
{
  tUInt8 DEF_aruser__h4946;
  tUInt8 DEF_fabric_v_to_slaves_1_m_arvalid____d60;
  tUInt8 DEF_boot_rom_slave_m_arready____d64;
  tUInt8 DEF_arprot__h4945;
  tUInt64 DEF_araddr__h4944;
  DEF_araddr__h4944 = INST_fabric.METH_v_to_slaves_1_m_araddr();
  DEF_arprot__h4945 = INST_fabric.METH_v_to_slaves_1_m_arprot();
  DEF_boot_rom_slave_m_arready____d64 = INST_boot_rom.METH_slave_m_arready();
  DEF_fabric_v_to_slaves_1_m_arvalid____d60 = INST_fabric.METH_v_to_slaves_1_m_arvalid();
  DEF_aruser__h4946 = INST_fabric.METH_v_to_slaves_1_m_aruser();
  INST_boot_rom.METH_slave_m_arvalid(DEF_fabric_v_to_slaves_1_m_arvalid____d60,
				     DEF_araddr__h4944,
				     DEF_arprot__h4945,
				     DEF_aruser__h4946);
  INST_fabric.METH_v_to_slaves_1_m_arready(DEF_boot_rom_slave_m_arready____d64);
}

void MOD_mkSoC_Top::RL_rl_rd_data_channel_3()
{
  tUInt8 DEF_ruser__h5009;
  tUInt8 DEF_fabric_v_to_slaves_1_m_rready____d69;
  tUInt8 DEF_boot_rom_slave_m_rvalid____d65;
  tUInt8 DEF_rresp__h5007;
  tUInt64 DEF_rdata__h5008;
  DEF_rdata__h5008 = INST_boot_rom.METH_slave_m_rdata();
  DEF_rresp__h5007 = INST_boot_rom.METH_slave_m_rresp();
  DEF_boot_rom_slave_m_rvalid____d65 = INST_boot_rom.METH_slave_m_rvalid();
  DEF_fabric_v_to_slaves_1_m_rready____d69 = INST_fabric.METH_v_to_slaves_1_m_rready();
  DEF_ruser__h5009 = INST_boot_rom.METH_slave_m_ruser();
  INST_fabric.METH_v_to_slaves_1_m_rvalid(DEF_boot_rom_slave_m_rvalid____d65,
					  DEF_rresp__h5007,
					  DEF_rdata__h5008,
					  DEF_ruser__h5009);
  INST_boot_rom.METH_slave_m_rready(DEF_fabric_v_to_slaves_1_m_rready____d69);
}

void MOD_mkSoC_Top::RL_rl_wr_addr_channel_4()
{
  tUInt8 DEF_awuser__h5122;
  tUInt8 DEF_brvf_core_cpu_slave_m_awready____d74;
  tUInt8 DEF_fabric_v_to_slaves_0_m_awvalid____d70;
  tUInt8 DEF_awprot__h5121;
  tUInt64 DEF_awaddr__h5120;
  DEF_awaddr__h5120 = INST_fabric.METH_v_to_slaves_0_m_awaddr();
  DEF_awprot__h5121 = INST_fabric.METH_v_to_slaves_0_m_awprot();
  DEF_fabric_v_to_slaves_0_m_awvalid____d70 = INST_fabric.METH_v_to_slaves_0_m_awvalid();
  DEF_brvf_core_cpu_slave_m_awready____d74 = INST_brvf_core.METH_cpu_slave_m_awready();
  DEF_awuser__h5122 = INST_fabric.METH_v_to_slaves_0_m_awuser();
  INST_brvf_core.METH_cpu_slave_m_awvalid(DEF_fabric_v_to_slaves_0_m_awvalid____d70,
					  DEF_awaddr__h5120,
					  DEF_awprot__h5121,
					  DEF_awuser__h5122);
  INST_fabric.METH_v_to_slaves_0_m_awready(DEF_brvf_core_cpu_slave_m_awready____d74);
}

void MOD_mkSoC_Top::RL_rl_wr_data_channel_4()
{
  tUInt8 DEF_brvf_core_cpu_slave_m_wready____d78;
  tUInt8 DEF_fabric_v_to_slaves_0_m_wvalid____d75;
  tUInt8 DEF_wstrb__h5213;
  tUInt64 DEF_wdata__h5212;
  DEF_wdata__h5212 = INST_fabric.METH_v_to_slaves_0_m_wdata();
  DEF_wstrb__h5213 = INST_fabric.METH_v_to_slaves_0_m_wstrb();
  DEF_fabric_v_to_slaves_0_m_wvalid____d75 = INST_fabric.METH_v_to_slaves_0_m_wvalid();
  DEF_brvf_core_cpu_slave_m_wready____d78 = INST_brvf_core.METH_cpu_slave_m_wready();
  INST_brvf_core.METH_cpu_slave_m_wvalid(DEF_fabric_v_to_slaves_0_m_wvalid____d75,
					 DEF_wdata__h5212,
					 DEF_wstrb__h5213);
  INST_fabric.METH_v_to_slaves_0_m_wready(DEF_brvf_core_cpu_slave_m_wready____d78);
}

void MOD_mkSoC_Top::RL_rl_wr_response_channel_4()
{
  tUInt8 DEF_buser__h5270;
  tUInt8 DEF_brvf_core_cpu_slave_m_bvalid____d79;
  tUInt8 DEF_fabric_v_to_slaves_0_m_bready____d82;
  tUInt8 DEF_bresp__h5269;
  DEF_bresp__h5269 = INST_brvf_core.METH_cpu_slave_m_bresp();
  DEF_fabric_v_to_slaves_0_m_bready____d82 = INST_fabric.METH_v_to_slaves_0_m_bready();
  DEF_brvf_core_cpu_slave_m_bvalid____d79 = INST_brvf_core.METH_cpu_slave_m_bvalid();
  DEF_buser__h5270 = INST_brvf_core.METH_cpu_slave_m_buser();
  INST_fabric.METH_v_to_slaves_0_m_bvalid(DEF_brvf_core_cpu_slave_m_bvalid____d79,
					  DEF_bresp__h5269,
					  DEF_buser__h5270);
  INST_brvf_core.METH_cpu_slave_m_bready(DEF_fabric_v_to_slaves_0_m_bready____d82);
}

void MOD_mkSoC_Top::RL_rl_rd_addr_channel_4()
{
  tUInt8 DEF_aruser__h5329;
  tUInt8 DEF_brvf_core_cpu_slave_m_arready____d87;
  tUInt8 DEF_fabric_v_to_slaves_0_m_arvalid____d83;
  tUInt8 DEF_arprot__h5328;
  tUInt64 DEF_araddr__h5327;
  DEF_araddr__h5327 = INST_fabric.METH_v_to_slaves_0_m_araddr();
  DEF_arprot__h5328 = INST_fabric.METH_v_to_slaves_0_m_arprot();
  DEF_fabric_v_to_slaves_0_m_arvalid____d83 = INST_fabric.METH_v_to_slaves_0_m_arvalid();
  DEF_brvf_core_cpu_slave_m_arready____d87 = INST_brvf_core.METH_cpu_slave_m_arready();
  DEF_aruser__h5329 = INST_fabric.METH_v_to_slaves_0_m_aruser();
  INST_brvf_core.METH_cpu_slave_m_arvalid(DEF_fabric_v_to_slaves_0_m_arvalid____d83,
					  DEF_araddr__h5327,
					  DEF_arprot__h5328,
					  DEF_aruser__h5329);
  INST_fabric.METH_v_to_slaves_0_m_arready(DEF_brvf_core_cpu_slave_m_arready____d87);
}

void MOD_mkSoC_Top::RL_rl_rd_data_channel_4()
{
  tUInt8 DEF_ruser__h5392;
  tUInt8 DEF_brvf_core_cpu_slave_m_rvalid____d88;
  tUInt8 DEF_fabric_v_to_slaves_0_m_rready____d92;
  tUInt8 DEF_rresp__h5390;
  tUInt64 DEF_rdata__h5391;
  DEF_rdata__h5391 = INST_brvf_core.METH_cpu_slave_m_rdata();
  DEF_rresp__h5390 = INST_brvf_core.METH_cpu_slave_m_rresp();
  DEF_fabric_v_to_slaves_0_m_rready____d92 = INST_fabric.METH_v_to_slaves_0_m_rready();
  DEF_brvf_core_cpu_slave_m_rvalid____d88 = INST_brvf_core.METH_cpu_slave_m_rvalid();
  DEF_ruser__h5392 = INST_brvf_core.METH_cpu_slave_m_ruser();
  INST_fabric.METH_v_to_slaves_0_m_rvalid(DEF_brvf_core_cpu_slave_m_rvalid____d88,
					  DEF_rresp__h5390,
					  DEF_rdata__h5391,
					  DEF_ruser__h5392);
  INST_brvf_core.METH_cpu_slave_m_rready(DEF_fabric_v_to_slaves_0_m_rready____d92);
}

void MOD_mkSoC_Top::RL_rl_wr_addr_channel_5()
{
  tUInt8 DEF_awuser__h5505;
  tUInt8 DEF_fabric_v_to_slaves_2_m_awvalid____d93;
  tUInt8 DEF_mem0_controller_slave_m_awready____d97;
  tUInt8 DEF_awprot__h5504;
  tUInt64 DEF_awaddr__h5503;
  DEF_awaddr__h5503 = INST_fabric.METH_v_to_slaves_2_m_awaddr();
  DEF_awprot__h5504 = INST_fabric.METH_v_to_slaves_2_m_awprot();
  DEF_mem0_controller_slave_m_awready____d97 = INST_mem0_controller.METH_slave_m_awready();
  DEF_fabric_v_to_slaves_2_m_awvalid____d93 = INST_fabric.METH_v_to_slaves_2_m_awvalid();
  DEF_awuser__h5505 = INST_fabric.METH_v_to_slaves_2_m_awuser();
  INST_mem0_controller.METH_slave_m_awvalid(DEF_fabric_v_to_slaves_2_m_awvalid____d93,
					    DEF_awaddr__h5503,
					    DEF_awprot__h5504,
					    DEF_awuser__h5505);
  INST_fabric.METH_v_to_slaves_2_m_awready(DEF_mem0_controller_slave_m_awready____d97);
}

void MOD_mkSoC_Top::RL_rl_wr_data_channel_5()
{
  tUInt8 DEF_fabric_v_to_slaves_2_m_wvalid____d98;
  tUInt8 DEF_mem0_controller_slave_m_wready____d101;
  tUInt8 DEF_wstrb__h5597;
  tUInt64 DEF_wdata__h5596;
  DEF_wdata__h5596 = INST_fabric.METH_v_to_slaves_2_m_wdata();
  DEF_wstrb__h5597 = INST_fabric.METH_v_to_slaves_2_m_wstrb();
  DEF_mem0_controller_slave_m_wready____d101 = INST_mem0_controller.METH_slave_m_wready();
  DEF_fabric_v_to_slaves_2_m_wvalid____d98 = INST_fabric.METH_v_to_slaves_2_m_wvalid();
  INST_mem0_controller.METH_slave_m_wvalid(DEF_fabric_v_to_slaves_2_m_wvalid____d98,
					   DEF_wdata__h5596,
					   DEF_wstrb__h5597);
  INST_fabric.METH_v_to_slaves_2_m_wready(DEF_mem0_controller_slave_m_wready____d101);
}

void MOD_mkSoC_Top::RL_rl_wr_response_channel_5()
{
  tUInt8 DEF_buser__h5654;
  tUInt8 DEF_fabric_v_to_slaves_2_m_bready____d105;
  tUInt8 DEF_mem0_controller_slave_m_bvalid____d102;
  tUInt8 DEF_bresp__h5653;
  DEF_bresp__h5653 = INST_mem0_controller.METH_slave_m_bresp();
  DEF_mem0_controller_slave_m_bvalid____d102 = INST_mem0_controller.METH_slave_m_bvalid();
  DEF_fabric_v_to_slaves_2_m_bready____d105 = INST_fabric.METH_v_to_slaves_2_m_bready();
  DEF_buser__h5654 = INST_mem0_controller.METH_slave_m_buser();
  INST_fabric.METH_v_to_slaves_2_m_bvalid(DEF_mem0_controller_slave_m_bvalid____d102,
					  DEF_bresp__h5653,
					  DEF_buser__h5654);
  INST_mem0_controller.METH_slave_m_bready(DEF_fabric_v_to_slaves_2_m_bready____d105);
}

void MOD_mkSoC_Top::RL_rl_rd_addr_channel_5()
{
  tUInt8 DEF_aruser__h5713;
  tUInt8 DEF_fabric_v_to_slaves_2_m_arvalid____d106;
  tUInt8 DEF_mem0_controller_slave_m_arready____d110;
  tUInt8 DEF_arprot__h5712;
  tUInt64 DEF_araddr__h5711;
  DEF_araddr__h5711 = INST_fabric.METH_v_to_slaves_2_m_araddr();
  DEF_arprot__h5712 = INST_fabric.METH_v_to_slaves_2_m_arprot();
  DEF_mem0_controller_slave_m_arready____d110 = INST_mem0_controller.METH_slave_m_arready();
  DEF_fabric_v_to_slaves_2_m_arvalid____d106 = INST_fabric.METH_v_to_slaves_2_m_arvalid();
  DEF_aruser__h5713 = INST_fabric.METH_v_to_slaves_2_m_aruser();
  INST_mem0_controller.METH_slave_m_arvalid(DEF_fabric_v_to_slaves_2_m_arvalid____d106,
					    DEF_araddr__h5711,
					    DEF_arprot__h5712,
					    DEF_aruser__h5713);
  INST_fabric.METH_v_to_slaves_2_m_arready(DEF_mem0_controller_slave_m_arready____d110);
}

void MOD_mkSoC_Top::RL_rl_rd_data_channel_5()
{
  tUInt8 DEF_ruser__h5776;
  tUInt8 DEF_fabric_v_to_slaves_2_m_rready____d115;
  tUInt8 DEF_mem0_controller_slave_m_rvalid____d111;
  tUInt8 DEF_rresp__h5774;
  tUInt64 DEF_rdata__h5775;
  DEF_rdata__h5775 = INST_mem0_controller.METH_slave_m_rdata();
  DEF_rresp__h5774 = INST_mem0_controller.METH_slave_m_rresp();
  DEF_mem0_controller_slave_m_rvalid____d111 = INST_mem0_controller.METH_slave_m_rvalid();
  DEF_fabric_v_to_slaves_2_m_rready____d115 = INST_fabric.METH_v_to_slaves_2_m_rready();
  DEF_ruser__h5776 = INST_mem0_controller.METH_slave_m_ruser();
  INST_fabric.METH_v_to_slaves_2_m_rvalid(DEF_mem0_controller_slave_m_rvalid____d111,
					  DEF_rresp__h5774,
					  DEF_rdata__h5775,
					  DEF_ruser__h5776);
  INST_mem0_controller.METH_slave_m_rready(DEF_fabric_v_to_slaves_2_m_rready____d115);
}

void MOD_mkSoC_Top::RL_rl_wr_addr_channel_6()
{
  tUInt8 DEF_awuser__h5889;
  tUInt8 DEF_fabric_v_to_slaves_3_m_awvalid____d116;
  tUInt8 DEF_uart0_slave_m_awready____d120;
  tUInt8 DEF_awprot__h5888;
  tUInt64 DEF_awaddr__h5887;
  DEF_awaddr__h5887 = INST_fabric.METH_v_to_slaves_3_m_awaddr();
  DEF_awprot__h5888 = INST_fabric.METH_v_to_slaves_3_m_awprot();
  DEF_uart0_slave_m_awready____d120 = INST_uart0.METH_slave_m_awready();
  DEF_fabric_v_to_slaves_3_m_awvalid____d116 = INST_fabric.METH_v_to_slaves_3_m_awvalid();
  DEF_awuser__h5889 = INST_fabric.METH_v_to_slaves_3_m_awuser();
  INST_uart0.METH_slave_m_awvalid(DEF_fabric_v_to_slaves_3_m_awvalid____d116,
				  DEF_awaddr__h5887,
				  DEF_awprot__h5888,
				  DEF_awuser__h5889);
  INST_fabric.METH_v_to_slaves_3_m_awready(DEF_uart0_slave_m_awready____d120);
}

void MOD_mkSoC_Top::RL_rl_wr_data_channel_6()
{
  tUInt8 DEF_fabric_v_to_slaves_3_m_wvalid____d121;
  tUInt8 DEF_uart0_slave_m_wready____d124;
  tUInt8 DEF_wstrb__h5981;
  tUInt64 DEF_wdata__h5980;
  DEF_wdata__h5980 = INST_fabric.METH_v_to_slaves_3_m_wdata();
  DEF_wstrb__h5981 = INST_fabric.METH_v_to_slaves_3_m_wstrb();
  DEF_uart0_slave_m_wready____d124 = INST_uart0.METH_slave_m_wready();
  DEF_fabric_v_to_slaves_3_m_wvalid____d121 = INST_fabric.METH_v_to_slaves_3_m_wvalid();
  INST_uart0.METH_slave_m_wvalid(DEF_fabric_v_to_slaves_3_m_wvalid____d121,
				 DEF_wdata__h5980,
				 DEF_wstrb__h5981);
  INST_fabric.METH_v_to_slaves_3_m_wready(DEF_uart0_slave_m_wready____d124);
}

void MOD_mkSoC_Top::RL_rl_wr_response_channel_6()
{
  tUInt8 DEF_buser__h6038;
  tUInt8 DEF_fabric_v_to_slaves_3_m_bready____d128;
  tUInt8 DEF_uart0_slave_m_bvalid____d125;
  tUInt8 DEF_bresp__h6037;
  DEF_bresp__h6037 = INST_uart0.METH_slave_m_bresp();
  DEF_uart0_slave_m_bvalid____d125 = INST_uart0.METH_slave_m_bvalid();
  DEF_fabric_v_to_slaves_3_m_bready____d128 = INST_fabric.METH_v_to_slaves_3_m_bready();
  DEF_buser__h6038 = INST_uart0.METH_slave_m_buser();
  INST_fabric.METH_v_to_slaves_3_m_bvalid(DEF_uart0_slave_m_bvalid____d125,
					  DEF_bresp__h6037,
					  DEF_buser__h6038);
  INST_uart0.METH_slave_m_bready(DEF_fabric_v_to_slaves_3_m_bready____d128);
}

void MOD_mkSoC_Top::RL_rl_rd_addr_channel_6()
{
  tUInt8 DEF_aruser__h6097;
  tUInt8 DEF_fabric_v_to_slaves_3_m_arvalid____d129;
  tUInt8 DEF_uart0_slave_m_arready____d133;
  tUInt8 DEF_arprot__h6096;
  tUInt64 DEF_araddr__h6095;
  DEF_araddr__h6095 = INST_fabric.METH_v_to_slaves_3_m_araddr();
  DEF_arprot__h6096 = INST_fabric.METH_v_to_slaves_3_m_arprot();
  DEF_uart0_slave_m_arready____d133 = INST_uart0.METH_slave_m_arready();
  DEF_fabric_v_to_slaves_3_m_arvalid____d129 = INST_fabric.METH_v_to_slaves_3_m_arvalid();
  DEF_aruser__h6097 = INST_fabric.METH_v_to_slaves_3_m_aruser();
  INST_uart0.METH_slave_m_arvalid(DEF_fabric_v_to_slaves_3_m_arvalid____d129,
				  DEF_araddr__h6095,
				  DEF_arprot__h6096,
				  DEF_aruser__h6097);
  INST_fabric.METH_v_to_slaves_3_m_arready(DEF_uart0_slave_m_arready____d133);
}

void MOD_mkSoC_Top::RL_rl_rd_data_channel_6()
{
  tUInt8 DEF_ruser__h6160;
  tUInt8 DEF_fabric_v_to_slaves_3_m_rready____d138;
  tUInt8 DEF_uart0_slave_m_rvalid____d134;
  tUInt8 DEF_rresp__h6158;
  tUInt64 DEF_rdata__h6159;
  DEF_rdata__h6159 = INST_uart0.METH_slave_m_rdata();
  DEF_rresp__h6158 = INST_uart0.METH_slave_m_rresp();
  DEF_uart0_slave_m_rvalid____d134 = INST_uart0.METH_slave_m_rvalid();
  DEF_fabric_v_to_slaves_3_m_rready____d138 = INST_fabric.METH_v_to_slaves_3_m_rready();
  DEF_ruser__h6160 = INST_uart0.METH_slave_m_ruser();
  INST_fabric.METH_v_to_slaves_3_m_rvalid(DEF_uart0_slave_m_rvalid____d134,
					  DEF_rresp__h6158,
					  DEF_rdata__h6159,
					  DEF_ruser__h6160);
  INST_uart0.METH_slave_m_rready(DEF_fabric_v_to_slaves_3_m_rready____d138);
}

void MOD_mkSoC_Top::RL_rl_wr_addr_channel_7()
{
  tUInt8 DEF_awuser__h6273;
  tUInt8 DEF_fabric_v_to_slaves_4_m_awvalid____d139;
  tUInt8 DEF_timer0_slave_m_awready____d143;
  tUInt8 DEF_awprot__h6272;
  tUInt64 DEF_awaddr__h6271;
  DEF_awaddr__h6271 = INST_fabric.METH_v_to_slaves_4_m_awaddr();
  DEF_awprot__h6272 = INST_fabric.METH_v_to_slaves_4_m_awprot();
  DEF_timer0_slave_m_awready____d143 = INST_timer0.METH_slave_m_awready();
  DEF_fabric_v_to_slaves_4_m_awvalid____d139 = INST_fabric.METH_v_to_slaves_4_m_awvalid();
  DEF_awuser__h6273 = INST_fabric.METH_v_to_slaves_4_m_awuser();
  INST_timer0.METH_slave_m_awvalid(DEF_fabric_v_to_slaves_4_m_awvalid____d139,
				   DEF_awaddr__h6271,
				   DEF_awprot__h6272,
				   DEF_awuser__h6273);
  INST_fabric.METH_v_to_slaves_4_m_awready(DEF_timer0_slave_m_awready____d143);
}

void MOD_mkSoC_Top::RL_rl_wr_data_channel_7()
{
  tUInt8 DEF_fabric_v_to_slaves_4_m_wvalid____d144;
  tUInt8 DEF_timer0_slave_m_wready____d147;
  tUInt8 DEF_wstrb__h6365;
  tUInt64 DEF_wdata__h6364;
  DEF_wdata__h6364 = INST_fabric.METH_v_to_slaves_4_m_wdata();
  DEF_wstrb__h6365 = INST_fabric.METH_v_to_slaves_4_m_wstrb();
  DEF_timer0_slave_m_wready____d147 = INST_timer0.METH_slave_m_wready();
  DEF_fabric_v_to_slaves_4_m_wvalid____d144 = INST_fabric.METH_v_to_slaves_4_m_wvalid();
  INST_timer0.METH_slave_m_wvalid(DEF_fabric_v_to_slaves_4_m_wvalid____d144,
				  DEF_wdata__h6364,
				  DEF_wstrb__h6365);
  INST_fabric.METH_v_to_slaves_4_m_wready(DEF_timer0_slave_m_wready____d147);
}

void MOD_mkSoC_Top::RL_rl_wr_response_channel_7()
{
  tUInt8 DEF_buser__h6422;
  tUInt8 DEF_fabric_v_to_slaves_4_m_bready____d151;
  tUInt8 DEF_timer0_slave_m_bvalid____d148;
  tUInt8 DEF_bresp__h6421;
  DEF_bresp__h6421 = INST_timer0.METH_slave_m_bresp();
  DEF_timer0_slave_m_bvalid____d148 = INST_timer0.METH_slave_m_bvalid();
  DEF_fabric_v_to_slaves_4_m_bready____d151 = INST_fabric.METH_v_to_slaves_4_m_bready();
  DEF_buser__h6422 = INST_timer0.METH_slave_m_buser();
  INST_fabric.METH_v_to_slaves_4_m_bvalid(DEF_timer0_slave_m_bvalid____d148,
					  DEF_bresp__h6421,
					  DEF_buser__h6422);
  INST_timer0.METH_slave_m_bready(DEF_fabric_v_to_slaves_4_m_bready____d151);
}

void MOD_mkSoC_Top::RL_rl_rd_addr_channel_7()
{
  tUInt8 DEF_aruser__h6481;
  tUInt8 DEF_fabric_v_to_slaves_4_m_arvalid____d152;
  tUInt8 DEF_timer0_slave_m_arready____d156;
  tUInt8 DEF_arprot__h6480;
  tUInt64 DEF_araddr__h6479;
  DEF_araddr__h6479 = INST_fabric.METH_v_to_slaves_4_m_araddr();
  DEF_arprot__h6480 = INST_fabric.METH_v_to_slaves_4_m_arprot();
  DEF_timer0_slave_m_arready____d156 = INST_timer0.METH_slave_m_arready();
  DEF_fabric_v_to_slaves_4_m_arvalid____d152 = INST_fabric.METH_v_to_slaves_4_m_arvalid();
  DEF_aruser__h6481 = INST_fabric.METH_v_to_slaves_4_m_aruser();
  INST_timer0.METH_slave_m_arvalid(DEF_fabric_v_to_slaves_4_m_arvalid____d152,
				   DEF_araddr__h6479,
				   DEF_arprot__h6480,
				   DEF_aruser__h6481);
  INST_fabric.METH_v_to_slaves_4_m_arready(DEF_timer0_slave_m_arready____d156);
}

void MOD_mkSoC_Top::RL_rl_rd_data_channel_7()
{
  tUInt8 DEF_ruser__h6544;
  tUInt8 DEF_fabric_v_to_slaves_4_m_rready____d161;
  tUInt8 DEF_timer0_slave_m_rvalid____d157;
  tUInt8 DEF_rresp__h6542;
  tUInt64 DEF_rdata__h6543;
  DEF_rdata__h6543 = INST_timer0.METH_slave_m_rdata();
  DEF_rresp__h6542 = INST_timer0.METH_slave_m_rresp();
  DEF_timer0_slave_m_rvalid____d157 = INST_timer0.METH_slave_m_rvalid();
  DEF_fabric_v_to_slaves_4_m_rready____d161 = INST_fabric.METH_v_to_slaves_4_m_rready();
  DEF_ruser__h6544 = INST_timer0.METH_slave_m_ruser();
  INST_fabric.METH_v_to_slaves_4_m_rvalid(DEF_timer0_slave_m_rvalid____d157,
					  DEF_rresp__h6542,
					  DEF_rdata__h6543,
					  DEF_ruser__h6544);
  INST_timer0.METH_slave_m_rready(DEF_fabric_v_to_slaves_4_m_rready____d161);
}

void MOD_mkSoC_Top::RL_rl_connect_software_interrupt_request()
{
  INST_timer0.METH_get_sw_interrupt_req_get();
  INST_brvf_core.METH_cpu_software_interrupt_req();
}

void MOD_mkSoC_Top::RL_rl_connect_timer_interrupt_request()
{
  tUInt8 DEF_timer0_get_timer_interrupt_req_get___d166;
  tUInt8 DEF_AVMeth_timer0_get_timer_interrupt_req_get;
  DEF_AVMeth_timer0_get_timer_interrupt_req_get = INST_timer0.METH_get_timer_interrupt_req_get();
  DEF_timer0_get_timer_interrupt_req_get___d166 = DEF_AVMeth_timer0_get_timer_interrupt_req_get;
  INST_brvf_core.METH_cpu_timer_interrupt_req(DEF_timer0_get_timer_interrupt_req_get___d166);
}

void MOD_mkSoC_Top::RL_rl_reset_complete()
{
  tUInt64 DEF_addr_base__h6839;
  tUInt64 DEF_addr_lim__h6840;
  tUInt64 DEF_addr_base__h6879;
  tUInt64 DEF_addr_lim__h6880;
  tUInt64 DEF_addr_base__h6917;
  tUInt64 DEF_addr_lim__h6918;
  tUInt64 DEF_addr_base__h6955;
  tUInt64 DEF_addr_lim__h6956;
  DEF_addr_lim__h6956 = INST_soc_map.METH_m_timer0_addr_lim();
  DEF_addr_base__h6955 = INST_soc_map.METH_m_timer0_addr_base();
  DEF_addr_lim__h6918 = INST_soc_map.METH_m_uart0_addr_lim();
  DEF_addr_base__h6917 = INST_soc_map.METH_m_uart0_addr_base();
  DEF_addr_lim__h6880 = INST_soc_map.METH_m_mem0_controller_addr_lim();
  DEF_addr_base__h6879 = INST_soc_map.METH_m_mem0_controller_addr_base();
  DEF_addr_lim__h6840 = INST_soc_map.METH_m_boot_rom_addr_lim();
  DEF_addr_base__h6839 = INST_soc_map.METH_m_boot_rom_addr_base();
  INST_brvf_core.METH_cpu_reset_server_response_get();
  INST_mem0_controller.METH_server_reset_response_get();
  INST_uart0.METH_server_reset_response_get();
  INST_timer0.METH_server_reset_response_get();
  INST_boot_rom.METH_set_addr_map(DEF_addr_base__h6839, DEF_addr_lim__h6840);
  INST_mem0_controller.METH_set_addr_map(DEF_addr_base__h6879, DEF_addr_lim__h6880);
  INST_uart0.METH_set_addr_map(DEF_addr_base__h6917, DEF_addr_lim__h6918);
  INST_timer0.METH_set_addr_map(DEF_addr_base__h6955, DEF_addr_lim__h6956);
  INST_rg_state.METH_write((tUInt8)2u);
}

void MOD_mkSoC_Top::RL_rl_reset_start_2()
{
  INST_brvf_core.METH_cpu_reset_server_request_put((tUInt8)0u);
  INST_mem0_controller.METH_server_reset_request_put((tUInt8)0u);
  INST_uart0.METH_server_reset_request_put((tUInt8)0u);
  INST_timer0.METH_server_reset_request_put((tUInt8)0u);
  INST_rg_state.METH_write((tUInt8)1u);
  INST_fabric.METH_reset();
}


/* Methods */

tUWide MOD_mkSoC_Top::METH_to_raw_mem_request_get()
{
  tUWide DEF_AVMeth_mem0_controller_to_raw_mem_request_get(353u, false);
  DEF_AVMeth_mem0_controller_to_raw_mem_request_get = INST_mem0_controller.METH_to_raw_mem_request_get();
  PORT_to_raw_mem_request_get = DEF_AVMeth_mem0_controller_to_raw_mem_request_get;
  return PORT_to_raw_mem_request_get;
}

tUInt8 MOD_mkSoC_Top::METH_RDY_to_raw_mem_request_get()
{
  tUInt8 DEF_CAN_FIRE_to_raw_mem_request_get;
  tUInt8 PORT_RDY_to_raw_mem_request_get;
  DEF_CAN_FIRE_to_raw_mem_request_get = INST_mem0_controller.METH_RDY_to_raw_mem_request_get();
  PORT_RDY_to_raw_mem_request_get = DEF_CAN_FIRE_to_raw_mem_request_get;
  return PORT_RDY_to_raw_mem_request_get;
}

void MOD_mkSoC_Top::METH_to_raw_mem_response_put(tUWide ARG_to_raw_mem_response_put)
{
  PORT_to_raw_mem_response_put = ARG_to_raw_mem_response_put;
  INST_mem0_controller.METH_to_raw_mem_response_put(ARG_to_raw_mem_response_put);
}

tUInt8 MOD_mkSoC_Top::METH_RDY_to_raw_mem_response_put()
{
  tUInt8 DEF_CAN_FIRE_to_raw_mem_response_put;
  tUInt8 PORT_RDY_to_raw_mem_response_put;
  DEF_CAN_FIRE_to_raw_mem_response_put = INST_mem0_controller.METH_RDY_to_raw_mem_response_put();
  PORT_RDY_to_raw_mem_response_put = DEF_CAN_FIRE_to_raw_mem_response_put;
  return PORT_RDY_to_raw_mem_response_put;
}

tUInt8 MOD_mkSoC_Top::METH_get_to_console_get()
{
  tUInt8 PORT_get_to_console_get;
  tUInt8 DEF_AVMeth_uart0_get_to_console_get;
  DEF_AVMeth_uart0_get_to_console_get = INST_uart0.METH_get_to_console_get();
  PORT_get_to_console_get = DEF_AVMeth_uart0_get_to_console_get;
  return PORT_get_to_console_get;
}

tUInt8 MOD_mkSoC_Top::METH_RDY_get_to_console_get()
{
  tUInt8 DEF_CAN_FIRE_get_to_console_get;
  tUInt8 PORT_RDY_get_to_console_get;
  DEF_CAN_FIRE_get_to_console_get = INST_uart0.METH_RDY_get_to_console_get();
  PORT_RDY_get_to_console_get = DEF_CAN_FIRE_get_to_console_get;
  return PORT_RDY_get_to_console_get;
}

void MOD_mkSoC_Top::METH_put_from_console_put(tUInt8 ARG_put_from_console_put)
{
  INST_uart0.METH_put_from_console_put(ARG_put_from_console_put);
}

tUInt8 MOD_mkSoC_Top::METH_RDY_put_from_console_put()
{
  tUInt8 DEF_CAN_FIRE_put_from_console_put;
  tUInt8 PORT_RDY_put_from_console_put;
  DEF_CAN_FIRE_put_from_console_put = INST_uart0.METH_RDY_put_from_console_put();
  PORT_RDY_put_from_console_put = DEF_CAN_FIRE_put_from_console_put;
  return PORT_RDY_put_from_console_put;
}


/* Reset routines */

void MOD_mkSoC_Top::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_uart0.reset_RST_N(ARG_rst_in);
  INST_timer0.reset_RST_N(ARG_rst_in);
  INST_soc_map.reset_RST_N(ARG_rst_in);
  INST_rg_state.reset_RST(ARG_rst_in);
  INST_mem0_controller.reset_RST_N(ARG_rst_in);
  INST_fabric.reset_RST_N(ARG_rst_in);
  INST_brvf_core.reset_RST_N(ARG_rst_in);
  INST_boot_rom.reset_RST_N(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkSoC_Top::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkSoC_Top::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_boot_rom.dump_state(indent + 2u);
  INST_brvf_core.dump_state(indent + 2u);
  INST_fabric.dump_state(indent + 2u);
  INST_mem0_controller.dump_state(indent + 2u);
  INST_rg_state.dump_state(indent + 2u);
  INST_soc_map.dump_state(indent + 2u);
  INST_timer0.dump_state(indent + 2u);
  INST_uart0.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkSoC_Top::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 4u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "to_raw_mem_request_get", 353u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "to_raw_mem_response_put", 256u);
  num = INST_rg_state.dump_VCD_defs(num);
  if (levels != 1u)
  {
    unsigned int l = levels == 0u ? 0u : levels - 1u;
    num = INST_boot_rom.dump_VCD_defs(l);
    num = INST_brvf_core.dump_VCD_defs(l);
    num = INST_fabric.dump_VCD_defs(l);
    num = INST_mem0_controller.dump_VCD_defs(l);
    num = INST_soc_map.dump_VCD_defs(l);
    num = INST_timer0.dump_VCD_defs(l);
    num = INST_uart0.dump_VCD_defs(l);
  }
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkSoC_Top::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkSoC_Top &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
  if (levels != 1u)
    vcd_submodules(dt, levels - 1u, backing);
}

void MOD_mkSoC_Top::vcd_defs(tVCDDumpType dt, MOD_mkSoC_Top &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 353u);
    vcd_write_x(sim_hdl, num++, 256u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.PORT_to_raw_mem_request_get) != PORT_to_raw_mem_request_get)
      {
	vcd_write_val(sim_hdl, num, PORT_to_raw_mem_request_get, 353u);
	backing.PORT_to_raw_mem_request_get = PORT_to_raw_mem_request_get;
      }
      ++num;
      if ((backing.PORT_to_raw_mem_response_put) != PORT_to_raw_mem_response_put)
      {
	vcd_write_val(sim_hdl, num, PORT_to_raw_mem_response_put, 256u);
	backing.PORT_to_raw_mem_response_put = PORT_to_raw_mem_response_put;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, PORT_to_raw_mem_request_get, 353u);
      backing.PORT_to_raw_mem_request_get = PORT_to_raw_mem_request_get;
      vcd_write_val(sim_hdl, num++, PORT_to_raw_mem_response_put, 256u);
      backing.PORT_to_raw_mem_response_put = PORT_to_raw_mem_response_put;
    }
}

void MOD_mkSoC_Top::vcd_prims(tVCDDumpType dt, MOD_mkSoC_Top &backing)
{
  INST_rg_state.dump_VCD(dt, backing.INST_rg_state);
}

void MOD_mkSoC_Top::vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkSoC_Top &backing)
{
  INST_boot_rom.dump_VCD(dt, levels, backing.INST_boot_rom);
  INST_brvf_core.dump_VCD(dt, levels, backing.INST_brvf_core);
  INST_fabric.dump_VCD(dt, levels, backing.INST_fabric);
  INST_mem0_controller.dump_VCD(dt, levels, backing.INST_mem0_controller);
  INST_soc_map.dump_VCD(dt, levels, backing.INST_soc_map);
  INST_timer0.dump_VCD(dt, levels, backing.INST_timer0);
  INST_uart0.dump_VCD(dt, levels, backing.INST_uart0);
}
